nkdAgility/azure-devops-migration-tools

- docs/faq.md
- docs/index.md
- docs/server-configuration.md
I noticed there was almost no information about using the WorkItemDeleteConfig, particularly how it actually worked with regards to the Area Path it looks under for work items. I've had a few people asking me about it when I was showing them the tool and had to dig into the code to find out about the _DeleteMe requirement. 
I've added a bit of documentation as a starting point which should probably be expanded upon at some point.
> Documentation for Work Item Delete processor

- GitVersion.yml
- src/VstsSyncMigrator.Core/Execution/MigrationContext/LinkMigrationContext.cs
... as they are also appearing as links in TFS.
This is a PR to isolate changes from the old PR #21.
> Link migration now does also fix shared steps of test cases

- GitVersion.yml
- docs/configuration.md
- docs/usage/command-line.md
- src/VstsSyncMigrator.Core/Configuration/Processing/TestPlansAndSuitsMigrationConfig.cs
- src/VstsSyncMigrator.Core/Execution/MigrationContext/TestPlansAndSuitsMigrationContext.cs
See original PR #21.
Separated changes, which are only related to the filtering test plans and suites by tags.
> Test plans (and all sub-suites of them) to be migrated can be filtered by tags

- GitVersion.yml
- src/VstsSyncMigrator.Core/Execution/FieldMaps/FieldValuetoTagMap.cs
Works without a specified regex pattern.
Supports non-string types properly.
Cleans out empty values to prevent some various errors.
> Support non-string values and empty regex

- docs/configuration.md
- docs/usage/command-line.md
- src/VstsSyncMigrator.Core/Configuration/FieldMap/FieldMergeMapConfig.cs
- src/VstsSyncMigrator.Core/Execution/FieldMaps/FieldMergeMap.cs
Converted the  configuration property to be the sole driver of the `FieldMergeMap` rather than using it in addition to a static-set value.  Set the configuration to a default and added null checking.  Updated documentation.
> #53 - FieldMergeMap - Fix null-exception due to `doneMatch` being set to `null`

- src/VstsSyncMigrator.Core/Execution/MigrationContext/WorkItemMigrationContext.cs
Adds counter for failures and report information at the end
Make counters write to log
> Improve logging in WorkItemMigrationContext

- src/VstsSyncMigrator.Core/Execution/MigrationContext/TestPlansAndSuitsMigrationContext.cs
Add ReflectedWorkitemId to Test Plans and Suites migrated by TestPlansAndSuitsMigrationContext, therefore allowing to import related attachment later by AttachementImportMigrationContext
Fixes AssignedTo field values for Test Plans and Suites migrated by TestPlansAndSuitsMigrationContext (Set original value, not who created the item)
> Improving test plans and suites migration

- src/VstsSyncMigrator.Console/App.config
- src/VstsSyncMigrator.Core/Execution/MigrationContext/TestPlansAndSuitsMigrationContext.cs
If team project name dont match  between source and target then VSTS-sync shows an error because the orginal query is used without any modifcations. 
Original error message:
TestPlansAndSuites:        FAILED DynamicTestSuite : 0 - <...> 73267: <...> Subsystem (Prio 1 Testcases) | TF51011: The specified iteration path does not exist. The error is caused by «'<...>\Version 1'».
vstssyncmigrator.exe Warning: 0 :   [EXCEPTION] Specified argument was out of the range of valid values.
Parameter name: id
> Change project name in Query-based test suites

- src/VstsSyncMigrator.Core/Execution/MigrationContext/WorkItemRevisionReplayMigrationContext.cs
For Work Item revision replay based migrations, adds the original entry in the "History" field to the migrated revision. This way, any discussions in the History field are migrated to the target system.
> Adds history entry for each migrated revision, so that "Discussion" is also migrated

- src/VstsSyncMigrator.Core/Execution/ComponentContext/WorkItemStoreContext.cs
- src/VstsSyncMigrator.Core/Execution/MigrationContext/TestConfigurationsMigrationContext.cs
- src/VstsSyncMigrator.Core/Execution/MigrationContext/TestPlansAndSuitsMigrationContext.cs
- src/VstsSyncMigrator.Core/Execution/MigrationContext/TestVeriablesMigrationContext.cs
- The reflected work item ID that is generated is not a valid URL
- The searches for test variables, variable values and configurations need to be case insensitive as they are in VSTS
- Fixes an issues where the query used for dynamic wasn't being updated correctly if you used the prefix project nodes attribute
> Fixes the following issues

- src/VstsSyncMigrator.Core/Execution/ComponentContext/WorkItemStoreContext.cs
This may apply to other scenarios, but I was migrating Test Plans and Suites and was receiving a null exception error because I spelled my Team Project as "myteamproject" instead of "MyTeamProject".
> Case insensitive project name wistore reference

- src/VstsSyncMigrator.Core/Execution/FieldMaps/FieldValueMap.cs
- src/VstsSyncMigrator.Core/Execution/MigrationContext/WorkItemRevisionReplayMigrationContext.cs
Avoids "cannot convert Int32 to string" exception on integer source fields.
> Make FieldValueMap work for non-string source values

- src/VstsSyncMigrator.Core/Configuration/EngineConfiguration.cs
- src/VstsSyncMigrator.Core/Execution/ComponentContext/WorkItemStoreContext.cs
- src/VstsSyncMigrator.Core/Execution/MigrationContext/AttachementImportMigrationContext.cs
- src/VstsSyncMigrator.Core/Execution/MigrationContext/HtmlFieldEmbeddedImageMigrationContext.cs
- src/VstsSyncMigrator.Core/Execution/MigrationContext/LinkMigrationContext.cs
- src/VstsSyncMigrator.Core/Execution/MigrationContext/WorkItemMigrationContext.cs
- src/VstsSyncMigrator.Core/Execution/MigrationContext/WorkItemRevisionReplayMigrationContext.cs
- src/VstsSyncMigrator.Core/MigrationEngine.cs
Things addressed in this pull request:
* Added support for a source reflected work item id. The field name and/or process name might be different from source and destination. So this will support for specifying both. For example source might be "SourceProcess/ReflectedWorkItemId" while destination be "DstProcess/ReflectedWorkItemId"
* Fixed file names in target work item attachments. It used to migrate as source VSTS/TFS URL + file-name separated by hash, and certain characters replaced. It's now the same file name as the one in the source work item.
* Removed excessive slashes in the reflective work item URLs so that the URLs stays valid.
> Fixing a couple of issues when migrating from VSTS to VSTS

- src/VstsSyncMigrator.Core/Configuration/EngineConfiguration.cs
- src/VstsSyncMigrator.Core/Configuration/FieldMap/FieldValueMapConfig.cs
- src/VstsSyncMigrator.Core/Execution/FieldMaps/FieldValueMap.cs
Allow default value for FieldValueMapConfig. This eliminates the need to specify each and every source & target value. This can especially handy when dealing with large lists (e.g. area / iteration paths).
> Allow default value for FieldValueMapConfig

- src/VstsSyncMigrator.Core/Execution/ProcessingContext/FixGitCommitLinks.cs
Fixes issue where same ProjectName for Source and Destination causes FixGitCommitLinks to fail (see #133).
> Resolve #133

- src/VstsSyncMigrator.Core/Execution/MigrationContext/WorkItemRevisionReplayMigrationContext.cs
Reversed node caching logic to make sure a node is validated if it has not been checked prior.
> #143 Reversed caching logic to validate nodes on revision migration.

- src/VstsSyncMigrator.Core/Execution/MigrationContext/WorkItemMigrationContext.cs
If SourceReflectedWorkItemIdFieldName was not provided, the migration would throw an exception for every migrated item.
Item would be saved in target repo, but in the end every migrated item was marked as failed.
> Solved issue with NullReferenceException.

- src/VstsSyncMigrator.Core/Configuration/Processing/WorkItemMigrationConfig.cs
- src/VstsSyncMigrator.Core/Execution/MigrationContext/WorkItemMigrationContext.cs
The first commit was tested by me via migration our VSTS instance.
Unfortunately, I don't have a chance to test the second one - do not writing the comments table title when there is no comments.
> Changes to eliminate redundant comments in migrated items

- src/VstsSyncMigrator.Console/Program.cs
- src/VstsSyncMigrator.Core/Configuration/EngineConfiguration.cs
- src/VstsSyncMigrator.Core/Execution/ComponentContext/WorkItemStoreContext.cs
- src/VstsSyncMigrator.Core/Execution/MigrationContext/AttachementExportMigrationContext.cs
- src/VstsSyncMigrator.Core/Execution/MigrationContext/AttachementImportMigrationContext.cs
- src/VstsSyncMigrator.Core/Execution/MigrationContext/WorkItemRevisionReplayMigrationContext.cs
- src/VstsSyncMigrator.Core/Execution/ProcessingContext/FixGitCommitLinks.cs
Hello @MrHinsh according your suggestion I have submitted  new Pull Request. 
My changes relate to the following files:
_**Program.cs**_ -  small changes set local time, start and end time, and last this is the name of the log file now is called as name of your json file.  In my case I have almost 15000 work items, so I used several configs with different query bit. This is helped me to reduce time of working tool, so I have run it in parallel mode. Works great :)
_**EngineConfiguration.cs, FixGitCommitLinks.cs**_ - added ability to use QueryBit in the json configuration file for FixGitCommitLinksConfig
Also added the ability to process ArtifactLinkType.Name = "Pull Request". 
**AttachementExportMigrationContext.cs, AttachementImportMigrationContext.cs** - little bit changed the approach …
> Small improvements

- src/VstsSyncMigrator.Core/Execution/ProcessingContext/FixGitCommitLinks.cs
When the "bits" variable was greater than 3, it was adding the string at index 2 twice. Once before the for loop, then the same index position again since the start index position (i) was also 2.
> Change start array int for extrapolation of commitId

- src/VstsSyncMigrator.Core/Configuration/Processing/HtmlFieldEmbeddedImageMigrationConfig.cs
- src/VstsSyncMigrator.Core/Execution/MigrationContext/HtmlFieldEmbeddedImageMigrationContext.cs
- Uses HttpClient instead of WebClient to fully prevent redirects
- Allow to skip 404 errors
- Allow to configure to delete the temporary images from disk
- Ability to set multiple source URL's for TFS matching
> 404 support, tfs url alias, delete temp files, new download method

- src/VstsSyncMigrator.Core/Execution/MigrationContext/WorkItemRevisionReplayMigrationContext.cs
If a TFS project uses iterations that start with the word "Iteration" (like the OOTB iterations "Iteration 1/2/3") or areas that start with the word "Area" the injection of the word "Iteration" / "Area" fails to a wrong replacement.
> Fix issue that areas / iterations cannot start with Area / Iteration

- src/VstsSyncMigrator.Core/Execution/MigrationContext/AttachementImportMigrationContext.cs
… when that file already exists.  Check if the file exists before performing the move and delete it.  See stack trace in Issue #232
> Fix for Issue #232 Move File throws exception

- src/VstsSyncMigrator.Core/Execution/MigrationContext/WorkItemRevisionReplayMigrationContext.cs
Allows the Closed Date, Activated Date and Resolved Date  to be changed.
I discovered that the value cannot be written in the revision where the change happens but in subsequent revisions this is not a problem.
To bypass the Closed Date issue a new revision needs to be added in the item to migrate. I was not able to do that in the code yet, but adding in the work item on the server to migrate ensures all date values are correctly passed.
> Status Dates Fixes

- docs/Processors/TeamMigrationConfig.md
- src/VstsSyncMigrator.Core/Configuration/Processing/TeamMigrationConfig.cs
- src/VstsSyncMigrator.Core/Execution/MigrationContext/TeamMigrationContext.cs
Add the ability to migrate TeamSettings from source Team Project to target Team Project.
Configuration and doc has been updated.
> Add TeamSettings migration

- src/VstsSyncMigrator.Console/Program.cs
- src/VstsSyncMigrator.Core/Execution/OMatics/AttachmentOMatic.cs
- src/VstsSyncMigrator.Core/Execution/OMatics/WorkItemLinkOMatic.cs
Fix applies to set changed by name to "migration" for all attachement…and link saves.
> Fix for edit name 

- src/VstsSyncMigrator.Core/Execution/MigrationContext/WorkItemMigrationContext.cs
This commit fixes the filter query to also use the QueryBit and OrderBit. This removes the likleyhood of hitting the Query limit.
> FixForFilterQuery

- src/VstsSyncMigrator.Console/Program.cs
- src/VstsSyncMigrator.Core/Configuration/EngineConfiguration.cs
Changed version matching for config to 2 digits to get rid of the constant change. Need to remember to update version when changing configs. +semver: minor
> Move to 2 digit version for config

- src/VstsSyncMigrator.Console/Program.cs
- src/VstsSyncMigrator.Core.Tests/EngineConfigurationTests.cs
- src/VstsSyncMigrator.Core/Configuration/EngineConfiguration.cs
- src/VstsSyncMigrator.Core/Configuration/TeamProjectConfig.cs
- src/VstsSyncMigrator.Core/Execution/ComponentContext/TeamProjectContext.cs
- src/VstsSyncMigrator.Core/Execution/ComponentContext/TestManagementContext.cs
- src/VstsSyncMigrator.Core/Execution/ComponentContext/WorkItemStoreContext.cs
- src/VstsSyncMigrator.Core/Execution/MigrationContext/FakeProcessor.cs
- src/VstsSyncMigrator.Core/Execution/MigrationContext/MigrationContextBase.cs
- src/VstsSyncMigrator.Core/Execution/MigrationContext/NodeStructuresMigrationContext.cs
- src/VstsSyncMigrator.Core/Execution/MigrationContext/TeamMigrationContext.cs
- src/VstsSyncMigrator.Core/Execution/MigrationContext/TestConfigurationsMigrationContext.cs
- src/VstsSyncMigrator.Core/Execution/MigrationContext/TestPlansAndSuitesMigrationContext.cs
- src/VstsSyncMigrator.Core/Execution/MigrationContext/WorkItemMigrationContext.cs
- src/VstsSyncMigrator.Core/Execution/MigrationContext/WorkItemPostProcessingContext.cs
- src/VstsSyncMigrator.Core/Execution/MigrationContext/WorkItemQueryMigrationContext.cs
- src/VstsSyncMigrator.Core/Execution/OMatics/RepoOMatic.cs
- src/VstsSyncMigrator.Core/Execution/ProcessingContext/CreateTeamFolders.cs
- src/VstsSyncMigrator.Core/Execution/ProcessingContext/ExportTeamList.cs
- src/VstsSyncMigrator.Core/Execution/ProcessingContext/FixGitCommitLinks.cs
- src/VstsSyncMigrator.Core/Execution/ProcessingContext/ProcessingContextBase.cs
- src/VstsSyncMigrator.Core/Execution/ProcessingContext/WorkItemDelete.cs
- src/VstsSyncMigrator.Core/Execution/ProcessingContext/WorkItemUpdate.cs
- src/VstsSyncMigrator.Core/Execution/ProcessingContext/WorkItemUpdateAreasAsTagsContext.cs
Added the ability to enable cross-project work item linking as per #354. This is slightly dangerous as you may have left over trial migrations with the RelectedWorkItemID set and this will find them. +semver: minor 
WARNING: Make sure you delete all prior runs or blank the RelectedWorkItemID field.
> Allow Cross-Project Linking of Work Items

- src/VstsSyncMigrator.Core/Execution/ComponentContext/WorkItemStoreContext.cs
- src/VstsSyncMigrator.Core/Execution/OMatics/RepoOMatic.cs
I've converted projects (on premise DevOps Server 2019 update1) with LinkMigration=true.
Source project workItems were linked to repos in different projects from the same source collection. In my first scenario all destination repos were in the same target project.
Next for different scenario, some of target repos were located in the same target collection in different project so I have added the second commit. In that commit I also simplified method
RepoOMatic.Create(string targetRepoName, GitRepositoryInfo sourceRepoInfo , MigrationEngine migrationEngine, IList<GitRepository> targetRepos)
cause I believe there were some now unused code remnants.
Please note that for both scenarios (source as well as target) I've added a condition: external repo link is migrated only if linked repo is …
> Links from workItem to repo in different projects

- src/VstsSyncMigrator.Console/Program.cs
#402
Should more gracefully handle case when FindPackagesById returns an empty collection
> Bugfix: Gracefully handle missing Chocolatey package when getting latest version number

- src/VstsSyncMigrator.Core/Execution/OMatics/RepoOMatic.cs
**Error:** When migrating work items with git PR links, these links throw errors and further (commit) links for this work item won't be processed.
**Solution:** Ignore and keep unknown links without throwing an error to process further links.
**Further information:** In DetermineFromLink a PR ("Git/PullRequestId") set RepistoryType to unknown (only allows "git/commit"). Unknown can't be processed by GitRepositoryInfo.Create (currently evaluates only Git and TFVC) and returns a null. sourceRepoInfo is set to null which breaks the loop.
**Error message:**
```
Cannot determine repository type from external link: vstfs:///Git/PullRequestId/053f67f5-24ab-4d51-b15e-49b2c62d1a2b%2ffab2c49f-af08-491a-866f-85e7ed774611%2f21
[Product Backlog Item][Complete:1/2][sid:3095  |Rev:5  ][tid:null   | …
```
> Bugfix: Ignore unknown repo types (i.e. Git/PullRequestId) to process further links

- src/VstsSyncMigrator.Core/Execution/MigrationContext/TeamMigrationContext.cs
team settings could not match with the name of the Target Team Project.
> fix migration of Teams including Prefix Project Name

- docs/Processors/WorkItemMigrationConfig.md
- src/VstsSyncMigrator.Core/Configuration/Processing/WorkItemMigrationConfig.cs
- src/VstsSyncMigrator.Core/Execution/MigrationContext/WorkItemMigrationContext.cs
**Issue:**
When migrating work items from Azure DevOps Services to Azure DevOps Server that contain revisions that changed the work item type you receive the following error:
```
TF401326: Invalid field status 'InvalidNotOldValue' for field 'System.WorkItemType'"
```
This is described here.
https://twitter.com/fokkoveegens/status/1206610220790820866
I've adjusted it so that it uses the latest revision's Work Item Type when creating it's initial shell work item, I think that's likely the work item type that is where you want to land anyway.
> 'SkipToFinalRevisedWorkItemType' feature added to handle scenario when changing Work Item Type in revisions

- src/VstsSyncMigrator.Core/Configuration/Processing/TestPlansAndSuitesMigrationConfig.cs
PrefixProjectToNodes is supposed to be false by default according to the documentation (https://github.com/nkdAgility/azure-devops-migration-tools/blob/master/docs/Processors/TestPlansAndSuitesMigrationConfig.md).
> Changing PrefixProjectToNodes to false

- README.md
The getting-started link was pointed at a markdown file. The file does exist, but it's served from the docs site as raw text. This PR fixes the issue by pointing to the getting-started page instead.
> Update getting-started link

- src/VstsSyncMigrator.Core/Configuration/EngineConfiguration.cs
- src/VstsSyncMigrator.Core/Configuration/Processing/WorkItemQueryMigrationConfig.cs
- src/VstsSyncMigrator.Core/Execution/MigrationContext/WorkItemQueryMigrationContext.cs
This feature will close #527 and add the ability to have a field mapping to the `WorkItemQueryMigrationConfig`. Add a `SourceToTargetFieldMappings` variable with:
```
"SourceToTargetFieldMappings": {
"Siemens.Importance": "Custom.SiemensImportance",
"Siemens.Objective.Type": "Custom.SiemensObjectiveType"
```
> Shared Queries migration with field map #527

- src/MigrationTools.CommandLine/MigrationTools.CommandLine.csproj
- src/MigrationTools.ConsoleUI/MigrationTools.ConsoleUI.csproj
- src/MigrationTools.Core.Configuration/MigrationTools.Core.Configuration.csproj
- src/MigrationTools.Services/MigrationTools.Services.csproj
- src/MigrationTools.Sinks.AzureDevOps/MigrationTools.Sinks.AzureDevOps.csproj
Apparently .net core don't by default have version numbers and they store them in another place. Added all version numbers to 0.0.0.0
> Add version numbers

- src/VstsSyncMigrator.Core/Execution/MigrationContext/WorkItemMigrationContext.cs
While the process would run successfully, it would pause at this point when logging, use up lots of memory, error, and proceed with the rest of its logic.
> Log the project name rather than the entire project object structure

- src/VstsSyncMigrator.Core/Execution/FieldMaps/FieldMergeMap.cs
The target field will always contain an empty string, but that doesn't mean the merge should be skipped.
> Don't skip merging the field when sourceField2 is empty

- src/VstsSyncMigrator.Core/Execution/ComponentContext/WorkItemStoreContext.cs
- src/VstsSyncMigrator.Core/Execution/MigrationContext/TestPlansAndSuitesMigrationContext.cs
- src/VstsSyncMigrator.Core/Execution/MigrationContext/WorkItemMigrationContext.cs
- src/VstsSyncMigrator.Core/Execution/OMatics/WorkItemLinkOMatic.cs
Fixes issue #526.
When migrating links, Right-hand work items can now be found on the target system based on the ReflectedWorkItemId field on the source system.
Now updated to resolve merge conflicts.
> Fixed links to workitems based on ReflectedWorkItemId 

- README.md
- docs/getting-started.md
- docs/index.md
- src/MigrationTools/Core/Configuration/FieldMapConfigJsonConverter.cs
- src/MigrationTools/Core/Configuration/JsonCreationConverter.cs
- src/MigrationTools/Core/Configuration/ProcessorConfigJsonConverter.cs
- src/VstsSyncMigrator.Extension/README.md
There are error when moving Config around due to the class full name being used. This has been removed so that future refactors don't cause problems.
> Removed class fullname from config

- src/MigrationTools/Core/Configuration/FieldMap/FieldLiteralMapConfig.cs
- src/MigrationTools/Core/Configuration/FieldMap/FieldtoFieldMapConfig.cs
- src/VstsSyncMigrator.Core/Execution/FieldMaps/FieldLiteralMap.cs
- src/VstsSyncMigrator.Core/Execution/FieldMaps/FieldToFieldMap.cs
- src/VstsSyncMigrator.Core/VstsSyncMigrator.Core.csproj
Add a new mapping type to allow fields in the target to be populated with literal values.
Allow the standard field mapping type to enter a literal value as a fall-back, so that fields required in the target but not source can be populated with valid data.
> Allow mapping of literal values

- README.md
- docs/index.md
I copied the markdown from the readme.md previously which is still working now [there](https://github.com/nkdAgility/azure-devops-migration-tools)
but for the docs was causing extra columns, realized that the release columns are duplicated
[reference](https://nkdagility.github.io/azure-devops-migration-tools/)
> fixed release link

- .editorconfig
- src/VstsSyncMigrator.Console/Properties/launchSettings.json
- src/VstsSyncMigrator.Core/Execution/MigrationContext/TestPlansAndSuitesMigrationContext.cs
- src/VstsSyncMigrator.Core/Execution/MigrationContext/WorkItemMigrationContext.cs
- src/VstsSyncMigrator.Core/Execution/OMatics/WorkItemLinkOMatic.cs
Fixes an error with linking parents when replaying a work items revisions and it's parent has changed. Should Resolve #452 which references the same thing. 
The Pr contains the changes from #580 as I was working in the same branch when I discovered the error. I can nuke the branch and get just the changes in it's own if there is issues with the way 580 was done.
> Change how we process parent/child links when LinkMigrationSaveEachAsAdded = true

- src/VstsSyncMigrator.Core/Execution/MigrationContext/WorkItemMigrationContext.cs
changed the destination/target project in the work item migration context, as it should be possible to migrate from one devops project to another, this was broken in recent changes
> fixed target project selection for work item migration

- ApplicationInsights.config
- MigrationTools.sln
- src/MigrationTools.ConsoleCore/MigrationTools.ConsoleCore.csproj
- src/MigrationTools.ConsoleCore/appsettings.json
- src/MigrationTools.ConsoleFull/MigrationTools.ConsoleFull.csproj
- src/MigrationTools.ConsoleFull/appsettings.json
- src/MigrationTools.Host/MigrationToolHost.cs
- src/MigrationTools.Tests/Services/TelemetryLoggerMock.cs
- src/MigrationTools/MigrationEngine.cs
- src/MigrationTools/Services/ITelemetryLogger.cs
- src/MigrationTools/Services/TelemetryClientAdapter.cs
- src/VstsSyncMigrator.Core.Tests/TelemetryLoggerMock.cs
I have migrated Application Insights to `AddApplicationInsightsTelemetryWorkerService`. This allowed us to delete the ApplicationInsights.config as well as move the `TelemetryClientAdapter` to the same instance as 'Serilog`.
Thanks for the suggestion @ovebastiansen 
I also created a new ApplicationInsights Key as the old one is costing £100/month :o which is excessive. Since many folks have forked and still use the tools with the OLD key I have deleted the old endpoint and created a new one.
> Migrate AI to Worker

- src/VstsSyncMigrator.Core/Execution/MigrationContext/WorkItemMigrationContext.cs
Should resolve #626 by mapping the type prior to calling CreateWorkItem_Shell in WorkItemMigrationContext
This was likely introduced by the Collapse revisions or before...
> Resolution for TypeDefinitionMaps failures

- src/MigrationTools.Clients.AzureDevops.ObjectModel/Clients/MigrationClient.cs
- src/MigrationTools/MigrationEngine.cs
There was a bug in the return type from CheckForNetworkCredentials where it glitched if the dynamic object was null.
> Fixed #637

- src/VstsSyncMigrator.Core/Execution/MigrationContext/TestPlansAndSuitesMigrationContext.cs
It looks like this line hasn't been properly adapted to the new logging component. This PR fixes the exception which is always been raised in that context:
> Fix IndexOutOfRangeException in TestPlansAndSuitesMigrationContext

- docs/Processors/WorkItemMigrationConfig.md
- src/MigrationTools/Configuration/Processing/WorkItemMigrationConfig.cs
Since we currently have a bug in the REST API we can set this to true to bypass the "changed work item type" rest fix.
> Default SkipToFinalRevisedWorkItemType to true

- docs/Processors/AttachementExportMigrationConfig.md
- docs/Processors/AttachementImportMigrationConfig.md
- docs/Processors/FixGitCommitLinksConfig.md
- docs/Processors/HtmlFieldEmbeddedImageMigrationConfig.md
- docs/Processors/LinkMigrationConfig.md
- docs/Processors/NodeStructuresMigrationConfig.md
- docs/Processors/TestVariablesMigrationConfig.md
- docs/Processors/WorkItemDeleteConfig.md
- docs/Processors/WorkItemMigrationConfig.md
- docs/Processors/WorkItemQueryMigrationConfig.md
- docs/Processors/WorkItemRevisionReplayMigrationConfig.md
- docs/Processors/WorkItemUpdateConfig.md
- docs/configuration.md
- docs/getting-started.md
- docs/index.md
Whilst working with a client to do a migration using 11.6 I found the current documentation somewhat misleading due to the number of older processors that have been rolled into the WorkItemMigration processor.
I have made an effort to
- Make sure any processor document that is not currently in source control is marked as obsolete on both the index page and its own page
- Made sure all the configuration options on source control are present in the docs
- General update of the configuration samples and file path to reflect the currently shipping product.
> Documentation update for 11.6

- src/MigrationTools/Configuration/Processing/TestVariablesMigrationConfig.cs
The TestVariablesMigrationConfig Processor was named TestV**e**riablesMigrationConfig
> Fixed typo

- src/MigrationTools/Configuration/MigrationClientConfigJsonConverter.cs
Anytime an `"ObjectType"` changes from one release to another (like the recent rename of `"TeamProjectConfig"` to `"TfsTeamProjectConfig"`, and the removal of namespaces from all `ObjectType` properties before that), previous config files stop working. Most of the time the runtime exception is not helpful. These types of errors are very difficult to debug without having the source migration tool's source code installed and debuggable.
Here's an example. It tells us nothing about which ObjectType is causing the issue:
This PR adds support for throwing a more helpful error message, and provides some JSON context so that the user knows exactly which section of the JSON caused the problem. 
Here's how it looks in the console as a result of this PR:
> Throw helpful error for unknown ObjectType

- docs/Processors/TeamMigrationConfig.md
- src/MigrationTools/Configuration/Processing/TeamMigrationConfig.cs
- src/VstsSyncMigrator.Core/Execution/MigrationContext/TeamMigrationContext.cs
This flag will allow the processor to effectively reset a target teams settings through the migration without deleting them and migrating again.
This PR will allow for resetting of iterations and area path configuration. I'm looking at team members at the moment to see if that is something that could go in easily or not off another flag 😀
> Add property FixTeamSettingsForExistingTeams to TeamMigrationContext

- src/MigrationTools.Clients.AzureDevops.ObjectModel/Enrichers/TfsWorkItemLinkEnricher.cs
Whenever the TFS->DevOps migration encounters certain unknown link types, it causes the entire application to crash. It would be nice to recover more gracefully and continue (originally raised in [this](https://stackoverflow.com/questions/64373473/unrecognized-resource-link-fixed-in-changeset) StackOverflow post). This PR addresses that issue by recovering, resetting the work item, and continuing. 
Originally I thought about hiding this behind a flag, but it doesn't seem to be overly useful to crash the entire migration just for a few broken links. Since the errors get written to the console anyway, migrators can easily see if there are problems, and work to address them. 
I'm not overly familiar with the internals of this project, so I'm not sure the implications of calling `Reset()` on …
> Recover on unknown link type

- src/VstsSyncMigrator.Core/Execution/MigrationContext/TeamMigrationContext.cs
If a team is not configured and in a broken state as shown below we don't want to attempt the update on the target team because it will break
> only migrate team settings if they are configured

- src/MigrationTools.Clients.AzureDevops.ObjectModel/Clients/TfsWorkItemQuery.cs
- src/MigrationTools.Clients.AzureDevops.ObjectModel/TfsExtensions.cs
When destination ADO have deleted related workitems (possibly because multiple executions), the deleted itens are returned on wiql queries, causing a chain of exceptions and related itens not being migrated.
> Fixes chain of exceptions when WI is deleted,

- src/MigrationTools.Clients.AzureDevops.ObjectModel/Clients/TfsWorkItemMigrationClient.cs
- src/VstsSyncMigrator.Core/Execution/MigrationContext/WorkItemMigrationContext.cs
Hi,
I just realized that the Feature _FilterWorkItemsThatAlreadyExistInTarget_ is broken in the latest version. (I swapped between v8 and v11 because we heavily customized the tool to our needs based on v8 and we used v11 just for TestPlan migration. Now I was at the point that we had to integrate our customizations into v11 which was quite annoying to do...)
That's how I fixed the NullReferenceException in _FilterWorkItemsThatAlreadyExistInTarget_ quick and dirty and wanted to share it instead of creating an Issue. Any suggestions for doing it more convenient is welcome.
In addition I changed `Count()` to `Count` as I touched the file anyways and `Count` is much faster as the `List` object knows its item count. The extension method on the other hand iterates through all elements and …
> Fix FilterExistingWorkItems

- src/MigrationTools.Clients.AzureDevops.ObjectModel/TfsExtensions.cs
- src/VstsSyncMigrator.Core/Execution/MigrationContext/TestPlansAndSuitesMigrationContext.cs
And another bug appeared. TestPlans and Suites can't be saved anymore as the object was written to the field instead of the string value.
I allowed myself to add my local logging improvements for invalid fields also because the current implementation with the Dictionary is hard to read and prints nonsense:
From my log file:
2020-11-02 13:13:55.054 +01:00 [DBG]    Invalid Field: [Id:{"CurrentRevisionWorkItemId":38290,"CurrentRevisionWorkItemRev":2,"CurrentRevisionWorkItemTypeName":"Microsoft.TeamFoundation.WorkItemTracking.Client.WorkItemType","IsDirty":true,"FieldReferenceName":"Custom.ReflectedWorkItemId","FieldValue":"REMOVED"}**/{CurrentRevisionWorkItemRev}][Type:{CurrentRevisionWorkItemTypeName}][IsDirty:{IsDirty}][ReferenceName:{FieldReferenceName}][Value: {FieldValue}]**
2020-11-02 …
> Fix AssignReflectedWorkItemId in TestPlansAndSuitesMigrationContext

- src/MigrationTools.Clients.AzureDevops.ObjectModel/Clients/TfsReflectedWorkItemId.cs
This bug was also nasty to find (because my VS somehow didn't stop on my conditional breakpoint because of LINQ's anonymous functions) and prevented links from being migrated for source projects with blanks in it. The regex used by `GetReflectedWorkItemId()` searches only for non whitespace characters. I changed it to `[\S ]+` instead to support blanks and made it compiled to not reinit it every time which is time-consuming.
> Fix ReflectedWorkItemId to support blanks in project names as this is allowed

- src/MigrationTools.Clients.AzureDevops.ObjectModel/TfsExtensions.cs
- src/MigrationTools.Clients.AzureDevops.ObjectModel/_Enginev1/Clients/TfsMigrationClient.cs
- src/MigrationTools.Clients.AzureDevops.ObjectModel/_Enginev1/Clients/TfsWorkItemMigrationClient.cs
- src/MigrationTools.Tests/Core/Clients/MigrationClientMock.cs
- src/MigrationTools.Tests/Core/Configuration/EngineConfigurationTests.cs
- src/MigrationTools/MigrationTools.csproj
- src/MigrationTools/ServiceCollectionExtensions.cs
- src/MigrationTools/Services/TelemetryClientAdapter.cs
- src/MigrationTools/_EngineV1/Clients/IMigrationClient.cs
- src/MigrationTools/_EngineV1/Containers/FieldMapContainer.cs
- src/VstsSyncMigrator.Core.Tests/MigrationEngineTests.cs
- src/VstsSyncMigrator.Core.Tests/VstsSyncMigrator.Core.Tests.csproj
- src/VstsSyncMigrator.Core/Execution/MigrationContext/WorkItemMigrationContext.cs
Unfortunately #680 was not enough to make PATs working. Here is the fix at least for `WorkItemMigrationContext`. Maybe there are additional issues with other processors we don't use.
Additionally you'll find 2 minor logging fixes in this PR which I revealed the last days.
> Make sure PAT is used for WorkItemStore and WitHttpClient also

- src/VstsSyncMigrator.Core/Execution/MigrationContext/WorkItemMigrationContext.cs
This change should fix #734 as the Validation routine should make sure that the ReflectedWorkItemId field is never missing from a WorkItemType. We should now quit if it happens.
> Change to ReflectedWorkItemId Field Setting Code

- src/MigrationTools.Clients.AzureDevops.ObjectModel/FieldMaps/FieldMapBase.cs
- src/MigrationTools.Clients.AzureDevops.ObjectModel/FieldMaps/FieldValueMap.cs
- src/MigrationTools.Clients.AzureDevops.ObjectModel/TfsExtensions.cs
- src/MigrationTools/_EngineV1/DataContracts/WorkItemData.cs
- src/VstsSyncMigrator.Core/Execution/MigrationContext/WorkItemMigrationContext.cs
This is the beginning of what needs to be done to make ReplayRevisons work properly. In addition I replaced RevisedDate with ChangedDate as according to https://docs.microsoft.com/en-us/azure/devops/reference/xml/reportable-fields-reference?view=azure-devops-2020 RevisedDate was misused.
Of course `RefactoredToUseWorkItemData` can be removed some day but I don't have the time to fix all maps right now (We won't use ReplayRevisions in our environment). This way at least the code keeps compilable.
Partially solves #741
> Update AsDictionary to use the field reference name as key and refactor FieldValueMap as example to work properly with ReplayRevisions

- docs/Reference/Processors/TfsTeamSettingsProcessor.json
- docs/Reference/Processors/TfsTeamSettingsProcessor.md
- src/MigrationTools.Clients.AzureDevops.ObjectModel/Processors/TfsTeamSettingsProcessorOptions.cs
With those changes, that TfsTeamSettingsProcessor can be executed. But the Teams won't get saved to the target Endpoint.
> Makes the TfsTeamSettingsProcessor runnable

- src/MigrationTools.Clients.AzureDevops.ObjectModel/Processors/TfsSharedQueryProcessorOptions.cs
- src/MigrationTools.Clients.AzureDevops.ObjectModel/Processors/TfsTeamSettingsProcessorOptions.cs
- src/MigrationTools/Processors/WorkItemProcessor/WorkItemTrackingProcessorOptions.cs
This fixes the Naming of the `Processor` Object so we don't have to set the processor twice
> Fixed Processor Naming

- docs/Reference/Generated/MigrationTools.Clients.AzureDevops.Rest.xml
- docs/Reference/Generated/MigrationTools.xml
- docs/Reference/Processors/AzureDevOpsPipelineProcessor.json
- docs/Reference/Processors/AzureDevOpsPipelineProcessor.md
- src/MigrationTools.Clients.AzureDevops.Rest/Processors/AzureDevOpsPipelineProcessor.cs
- src/MigrationTools.Clients.AzureDevops.Rest/Processors/AzureDevOpsPipelineProcessorOptions.cs
- src/MigrationTools/DataContracts/Mapping.cs
- src/MigrationTools/DataContracts/Pipelines/BuildDefinitions.cs
- src/MigrationTools/DataContracts/Pipelines/ReleaseDefinitions.cs
- src/MigrationTools/DataContracts/Pipelines/TaskGroups.cs
- src/MigrationTools/DataContracts/Pipelines/VariableGroups.cs
- src/MigrationTools/DataContracts/RestApiDefinition.cs
- src/MigrationTools/Tests/TestingConstants.cs
- Add migration of Task and Variable Groups
- Map their IDs to the new ones in the target environment so Pipelines can reference them
Unfortunately, the nice Generic code isn't as pretty anymore since I had to add a method for every Definition Type. That is because their Structure differs too much from each other.
> AzureDevOps Pipeline Processor: Task- and Variable Groups

- src/MigrationTools.Clients.AzureDevops.ObjectModel/_Enginev1/Clients/TfsWorkItemMigrationClient.cs
Upgrading from 11.9.6 to 11.9.17 started throwing a "Object reference not set to an instance of an object" error. 
For this particular work item, it has the field for reflectedWorkItemId, (named "Custom.ReflectedWorkItemId"), but the value is empty string. 
This PR fixes the runtime error, but I don't know enough about the project to know if this is actually the right fix. Perhaps we should be preventing work items with null reflectedWorkItemIds from getting to this function upstream somewhere, or perhaps this will happen for every "new" work item. I'll need someone more familiar with the project to review and verify this is the right fix.
> fix null reference runtime exception

- src/MigrationTools.Extension/README.md
- src/MigrationTools.Extension/vss-extension.json
- src/VstsSyncMigrator.Core/Execution/MigrationContext/TestPlansAndSuitesMigrationContext.cs
I think this error is due to Log.LogError being different from Serilog. 
```
Log.LogError(ex, " FAILED {TestSuiteType} : {Id} - {Title}",
new Dictionary<string, string> {
{ "Name", Name},
{ "Target Project", Engine.Target.Config.AsTeamProjectConfig().Project},
{ "Target Collection", Engine.Target.Config.AsTeamProjectConfig().Collection.ToString() },
{ "Source Project", Engine.Source.Config.AsTeamProjectConfig().Project},
{ "Source Collection", Engine.Source.Config.AsTeamProjectConfig().Collection.ToString() },
{ "Status", Status.ToString() },
{ "Task", "SaveNewTestSuitToPlan" },
{ "Id", newTestSuite.Id.ToString()},
{ "Title", newTestSuite.Title},
{ "TestSuiteType", newTestSuite.TestSuiteType.ToString()}
});
```
The code above is invalid as the OOB logger cant parse the dictionary. I think …
> TestPlansAndSuitesMigrationContext crashes with System.IndexOutOfRangeException

- docs/Reference/Generated/MigrationTools.Clients.AzureDevops.Rest.xml
- src/MigrationTools.Clients.AzureDevops.Rest/Endpoints/AzureDevOpsEndpoint.cs
- src/MigrationTools.Clients.AzureDevops.Rest/Processors/AzureDevOpsPipelineProcessor.cs
- src/MigrationTools/DataContracts/Pipelines/BuildDefinitions.cs
- src/MigrationTools/DataContracts/Pipelines/TaskGroups.cs
The processor can now migrate multiple Versions of Task Groups and reference Service Connections to Pipelines
> Several fixes to the Pipeline Processor (again😄)

- src/MigrationTools.Clients.AzureDevops.Rest/Endpoints/AzureDevOpsEndpoint.cs
- src/MigrationTools.Clients.AzureDevops.Rest/Processors/AzureDevOpsPipelineProcessor.cs
- src/MigrationTools/DataContracts/Pipelines/BuildDefinitions.cs
- src/MigrationTools/DataContracts/Pipelines/ReleaseDefinitions.cs
- src/MigrationTools/DataContracts/Pipelines/ServiceConnection.cs
- src/MigrationTools/DataContracts/Pipelines/TaskGroups.cs
- src/MigrationTools/DataContracts/Pipelines/VariableGroups.cs
- src/MigrationTools/DataContracts/RestApiDefinition.cs
Since the Pipeline / Definition gets reset (because the DevOps REST API doesn't accept some incoming values such as "Id") and the mapping is made afterward, to initial Id is gone.
Because of that, the mapping isn't resolved properly when running all pipeline options after each other. If you run just one option e.x VariableGroups, stop the Tool and then just migrate Release Definitions which use that Variable Groups, the mapping would be right since it is now created by comparing target and source names, instead of Ids. -> Id comparison/lookup is just used when creating a Definition
This PR changes that behavior. Before resetting the Definition, the initial Id gets set into a private variable, which later on (when the mapping gets created) is received again.
This way
> Repair sourceId <-> targetId mapping for Pipeline Processor

- src/MigrationTools.Clients.AzureDevops.ObjectModel/Enrichers/TfsWorkItemLinkEnricher.cs
This should fix #964 but might break for other registered link types. Always check the log for `RelatedLink is of ArtifactLinkType` data.
> This should fix #964

- src/MigrationTools.Clients.AzureDevops.ObjectModel/FieldMaps/FieldBlankMap.cs
A fix to FieldBlankMap to work with all types and avoid invalid value assignments.
The fix Initializes the field's value to be the "OriginalValue" of the field.
Also checks and avoids some cases where work items would be invalid and logs to Debug level.
I've tested with all system fields and many fields from inherited agile process and it seems to work as expected.
> #969 - A fix to FieldBlankMap to work with all types and avoid invalid value assignments.

- src/VstsSyncMigrator.Core/Execution/MigrationContext/TestPlansAndSuitesMigrationContext.cs
Was logging like this:
[14:23:07 INF] No e-mail address known in source system for [{sourceIdentity.DisplayName}]. Cannot translate to target.
> Fix cannot translate to target message to display the testers name.

- src/MigrationTools/_EngineV1/Configuration/Processing/WorkItemMigrationConfig.cs
- src/VstsSyncMigrator.Core/Execution/MigrationContext/WorkItemMigrationContext.cs
Adds the ability to enable/disable NodeStructureEnricher via configuration in case you want to handle nodes manually.
- Added NodeStructureEnricherEnabled to configuration.
- NodeStructureEnricherEnabled defaults to true if no value is provided.
- NodeStructureEnricher Enabled is now controlled via the NodeStructureEnricherEnabled config value.
> Disable NodeStructureEnricher via configuration

- src/MigrationTools.Clients.AzureDevops.ObjectModel.Tests/ProcessorEnrichers/TfsNodeStructureTests.cs
- src/MigrationTools.Clients.AzureDevops.ObjectModel/ProcessorEnrichers/TfsNodeStructure.cs
Corrected an issue where the code was not mapping node names correctly. It should have been Removing nodePath (Area or Iteration) from path for correct population in work item. But it was removing the entire mapping. #1006
> Fix Node Naming issue

- src/MigrationTools.Clients.AzureDevops.ObjectModel/Enrichers/TfsWorkItemLinkEnricher.cs
- src/MigrationTools.Clients.AzureDevops.ObjectModel/FieldMaps/FieldBlankMap.cs
- src/MigrationTools.Clients.AzureDevops.ObjectModel/ProcessorEnrichers/TfsNodeStructure.cs
- src/MigrationTools.Clients.AzureDevops.ObjectModel/TfsExtensions.cs
- src/MigrationTools.Clients.AzureDevops.ObjectModel/_Enginev1/Clients/TfsWorkItemQuery.cs
- src/MigrationTools.Clients.AzureDevops.Rest/Endpoints/AzureDevOpsEndpoint.cs
- src/MigrationTools.Clients.AzureDevops.Rest/Processors/ProcessDefinitionProcessor.cs
- src/MigrationTools/Endpoints/EndpointFactory.cs
- src/MigrationTools/Processors/Processor.cs
- src/MigrationTools/_EngineV1/Configuration/EngineConfigurationBuilder.cs
A small change that came from a 2 day headache, trying to figure out what I needed to do - The source project name was wrong by one letter that didn't have the right case.  So I changed the function to disregard case sensitivity in the node search (area/iteration).
The rest was more oriented to logging and VS Debugging experience.  When running from VS, the version mismatch between the file and migration is disregarded.
Pat
> A few tweaks to debugging and logging, and a made node path search case insensitive

- docs/Reference/Generated/MigrationTools.Clients.AzureDevops.Rest.xml
- src/MigrationTools.Clients.AzureDevops.Rest.Tests/Processors/AzureDevOpsPipelineProcessorTests.cs
- src/MigrationTools.Clients.AzureDevops.Rest.Tests/Processors/AzureDevOpsProcessorTests.cs
- src/MigrationTools.Clients.AzureDevops.Rest/Processors/AzureDevOpsPipelineProcessor.cs
- src/MigrationTools.Clients.AzureDevops.Rest/Processors/AzureDevOpsPipelineProcessorOptions.cs
- src/MigrationTools.TestExtensions/MigrationTools.TestExtensions.csproj
- src/MigrationTools.TestExtensions/ServiceCollectionExtensions.cs
This enables the ability to select the build and/or release pipelines to be migrated. It builds a list of query tasks based on the list provided in the configuration and tries to migrate them like before. If the configuration is not set or an empty list is provided, then then it queries for all the definitions like before. 
Also sets the repository query not to get additional details as they did not appear to be used and in the case of disabled repositories, will throw an error and stop the migration of the pipelines even if they aren't the ones being referenced in the build definitions.
Added a couple of tests as well as the [InMemory Serilog](https://github.com/serilog-contrib/SerilogSinksInMemory) package to make asserting for the correct logs easier. 
Tested via a DevOps Service to …
> Implement selecting build/release pipelines for migration

- src/MigrationTools.Clients.AzureDevops.ObjectModel/Enrichers/TfsWorkItemLinkEnricher.cs
TfsWorkItemLinkEnricher.CreateHyperlink(...) uses .SingleOrDefault() which throws an InvalidOperationException if more than 1 instances exist in an enumerable.
Looking at the code (and knowing how TFS/Azure DevOps Server/Services behave when trying to add the very same Hyperlink twice) I'd _assume_ the previous code was also theoretically fine, but apparently one way or another at least one of our work item managed to get the very same hyperlink because whenever I run (v11.11.23) of the migration tools, I get the following exception:
```
[15:00:05 INF] Found 22 revisions to migrate on  Work item:32134
[15:00:05 INF] Found 0 revisions to migrate on  Work item:32134
[15:00:05 INF] [          User Story][Complete:    26/67][sid: 32134|Rev: 22][tid:  null | Links 3 | LinkMigrator:True …
```
> Fixes InvalidOperationException in TfsWorkItemLinkEnricher.CreateHyperlink(...)'s .SingleOrDefault() usage

- src/MigrationTools.Clients.AzureDevops.ObjectModel/Enrichers/TfsWorkItemEmbededLinkEnricher.cs
- src/MigrationTools.Clients.AzureDevops.ObjectModel/ServiceCollectionExtensions.cs
- src/VstsSyncMigrator.Core/Execution/MigrationContext/WorkItemMigrationContext.cs
Enhancement to fix inline workitem mention links as well as like for like person/user mentions on all the HTML fields as well as discussion comment history. It uses *FixHtmlAttachmentLinks* flag on the configuration so if true, it processes otherwise it does not.
Please note that the user mentions will flood the user with lots of notification emails. To avoid sending notification emails, remove the user from the Target Team Project but the user need to exists on the Target Organisation.
Might need documentation update but I am not sure how or where to go by updating it.
Fixes # (issue)
#416 
#115 
#587 
I have tested it on my production migration from Azure DevOps Server to Azure DevOps Services for inline workitem mentions as well as person/user mentions on html fields as well as …
> Enhancement to fix inline workitem/user mention links on HTML fields as well as Comments history 

- src/MigrationTools.Clients.AzureDevops.ObjectModel/Enrichers/TfsEmbededImagesEnricher.cs
- src/MigrationTools/DataContracts/Pipelines/BuildDefinitions.cs
- src/VstsSyncMigrator.Core/Execution/MigrationContext/WorkItemMigrationContext.cs
Made some changes on `TfsEmbededImagesEnricher` to replaced the hack of uploading an image as attachment on workitem, saving workitem, removing the attachment and saving again with just the attachment upload api without needing to save the work item. 
Also enhanced this `TfsEmbededImagesEnricher` in addition with `WorkItemMigrationContext` to be able to make it work on discussion history comments as it was not working for history comments. 
Fixes # (issue)
#424 
May be also fixes #276 ?
I have tested it on my production migration from Azure DevOps Server to Azure DevOps Services for inline images in all the HTML fields as well as discussion comments history.
> Fix for Inline Images In Comments

- src/VstsSyncMigrator.Core.Tests/WorkItemMigrationTests.cs
- src/VstsSyncMigrator.Core/Execution/MigrationContext/WorkItemMigrationContext.cs
There was a problem with the existing code where it tries to replace the source project name with target project name for System.AreaPath filter WIQLQueryBit. 
Before this change, the code only worked for AreaPath filter. Also it was dependent on NodeBasePaths which seems wrong. It did not work when using UNDER operator.
The above is fixed with this change. An enhancement is added so that it also works for IterationPath filter and it no longer depends on NodeBasePaths. Existing unit tests are updated and couple new added.
Might need documentation update but I am not sure how or where to go by updating it.
Fixes #396 
I have tested it on my production migration from Azure DevOps Server to Azure DevOps Services when using System.AreaPath and System.IterationPath filters on the WIQLQueryBit.
> WIQLQueryBit Area Path & Iteration Path replacing source project with target project fix and enhancement

- docs/Reference/Processors/TfsTeamSettingsProcessor.json
- docs/Reference/Processors/TfsTeamSettingsProcessor.md
- src/MigrationTools.Clients.AzureDevops.ObjectModel/Endpoints/TfsTeamSettingsEndpoint.cs
- src/MigrationTools.Clients.AzureDevops.ObjectModel/Processors/TfsTeamSettingsProcessor.cs
- src/MigrationTools.Clients.AzureDevops.ObjectModel/Processors/TfsTeamSettingsProcessorOptions.cs
Enhancement added to `TfsTeamSettingsProcessor` to migrate team capacities. A new boolean option `MigrateTeamCapacities` is also added to `TfsTeamSettingsProcessorOptions`. And relevant documentation updated too.
Please note that It will only migrate team member capacity if the team member with same display name exists on the target collection otherwise it will be ignored.
It might fix part of #868 
I have tested it on my production migration from Azure DevOps Server to Azure DevOps Services.
> Enhancement added to TfsTeamSettingsProcessor to migrate team capacities

- CONTRIBUTING.md
I was looking into the code and was considering attempting to make some changes to the codebase and so I read the contribution file and found some issues that I figured I would try and fix first.
Lots of references to the old name of VSTS Sync Migration. Changed github and stackoverflow links using the new Azure Dev OPs naming.
There was a link to a coding guidelines document that doesn't exist. I didn't delete the _"requirement"_ but removed the link and changed with a placeholder. For anyone managing this pull request, if you feel like you want to add back the coding guidelines or remove the requirement in the markdown or another option that is fine.
Also, there was a reference to posting PRs to a TypeScript repo, so I removed that.
> adjusted naming from old VSTS to ADO, removed 404 link

- docs/getting-started.md
- docs/server-configuration.md
- Fix name of EXE file (`migrate.exe` -> `migration.exe`)
- Adjust version of configuration.json sample to 11.12
- Change title of last section from "Set minimum info and execute configuration.json" to "How to execute configuration.json with minimal adjustments"
- Remember users, that custom field "ReflectedWorkItemId" has to be added to both, source and target team project
- Improve wording of last section for better understandability
- Formatting
- Change "workflow types" to "work item types"
- Adjust TIP to avoid misinterpretation
- Adjust configuration sample by adding Source and Target object context, removing unnecessary attributes and changing QueryBit to WIQLQueryBit
- Fix typos
- Formatting
> Update and improve getting started and server configuration documentation

- src/VstsSyncMigrator.Core.Tests/WorkItemMigrationTests.cs
- src/VstsSyncMigrator.Core/Execution/MigrationContext/WorkItemMigrationContext.cs
Fixed the issue with target query when PrefixProjectToNodes is enabled. It was throwing area/iteration path not found on the target server.
I have tested it on my production migration from Azure DevOps Server to Azure DevOps Services.
> Fixed the issue with target query when PrefixProjectToNodes is enabled

- docs/Processors/TestPlansAndSuitesMigrationConfig.md
- docs/Processors/WorkItemMigrationConfig.md
- docs/Reference/Generated/MigrationTools.Clients.AzureDevops.ObjectModel.xml
- docs/configuration.md
- src/MigrationTools.Clients.AzureDevops.ObjectModel.Tests/ProcessorEnrichers/TfsNodeStructureTests.cs
- src/MigrationTools.Clients.AzureDevops.ObjectModel.Tests/ServiceProviderHelper.cs
- src/MigrationTools.Clients.AzureDevops.ObjectModel/ProcessorEnrichers/TfsNodeStructure.cs
- src/MigrationTools.Clients.AzureDevops.ObjectModel/ProcessorEnrichers/TfsNodeStructureOptions.cs
- src/MigrationTools.Clients.AzureDevops.ObjectModel/Processors/TfsAreaAndIterationProcessor.cs
- src/MigrationTools.Clients.AzureDevops.ObjectModel/Processors/TfsAreaAndIterationProcessorOptions.cs
- src/MigrationTools.ConsoleFull/Properties/launchSettings.json
- src/MigrationTools.Host/MigrationToolHost.cs
- src/MigrationTools/MigrationEngine.cs
- src/MigrationTools/_EngineV1/Configuration/EngineConfiguration.cs
- src/MigrationTools/_EngineV1/Configuration/Processing/TestPlansAndSuitesMigrationConfig.cs
- src/MigrationTools/_EngineV1/Configuration/Processing/WorkItemMigrationConfig.cs
- src/VstsSyncMigrator.Core.Tests/VstsSyncMigrator.Core.Tests.csproj
- src/VstsSyncMigrator.Core.Tests/WorkItemMigrationTests.cs
- src/VstsSyncMigrator.Core/Execution/MigrationContext/TestPlansAndSuitesMigrationContext.cs
- src/VstsSyncMigrator.Core/Execution/MigrationContext/WorkItemMigrationContext.cs
This commit implements area and iteration path remapping, which includes
- Remap area and iteration paths during node creation
- Remap area and iteration paths when migrating work items
This is compatible with the `PrefixProjectToNode` option, which is implemented as a "last resort" rule for the remapping.
> Implement area and iteration remapping

- docs/getting-started.md
- src/MigrationTools.Clients.AzureDevops.ObjectModel/_EngineV1/Configuration/TfsTeamProjectConfig.cs
- src/MigrationTools.Clients.AzureDevops.ObjectModel/_Enginev1/Clients/TfsMigrationClient.cs
This commit allows loading PATs from environment variables, which in turns makes it easier to store configuration files in source control.
> [feature] Get PAT from environment variables

- src/MigrationTools.Clients.AzureDevops.ObjectModel/Processors/TfsTeamSettingsProcessor.cs
Fixed the issue with replacing source project name with target project name when migrating Team Settings. It was replacing every occurrence source project name string and causing issues. So changed it to only replace the first occurrence on the path hierarchy.  
I have tested it on my production migration from Azure DevOps Server to Azure DevOps Services.
> TeamSettings project name replacement issue

- docs/Processors/WorkItemMigrationConfig.md
- docs/Reference/Generated/MigrationTools.Clients.AzureDevops.ObjectModel.xml
- src/MigrationTools.Clients.AzureDevops.ObjectModel/ProcessorEnrichers/TfsNodeStructure.cs
This commit introduces negative basepaths, i.e. base paths that are ignored even if they are under a selected basepath.
This means that if /path1 and !/path1/path2 are both in the basepaths, path2 and anything under it are ignored.
> Feature: support negative basepaths

- src/MigrationTools.Clients.AzureDevops.ObjectModel/Endpoints/TfsWorkItemConvertor.cs
- src/MigrationTools.Clients.AzureDevops.ObjectModel/TfsExtensions.cs
- src/VstsSyncMigrator.Core/Execution/MigrationContext/WorkItemMigrationContext.cs
This means that the revision number does not go up, and this ToDictionary call fails.
@MrHinsh Do you think we need a "backwards do not enable" flag in config so that we don't enable this fix by default? Since we are not getting alot of reports of this happening either people does not know or I have running into a freak case. In my case there was alot of revisions popping up in the list that was representing a link change, aka parent removed or similar
The fault does not break the run, you only spots that some revisions are missing, and that there are no reflectedworkitem written to the custom field and no migration comment in the history
> added a safety fix for when save ends up as a no-operation

- docs/Reference/Generated/MigrationTools.xml
- src/MigrationTools/_EngineV1/Configuration/Processing/WorkItemMigrationConfig.cs
- src/VstsSyncMigrator.Core/Execution/MigrationContext/WorkItemMigrationContext.cs
This Pull Request addresses an issue found whereby a revision in the source Azure DevOps instance has a deleted iteration path, and when the migration occurs, we had an error as the deleted iteration path is understandably not migrated to the target system. Azure DevOps will not allow null Iteration Paths, so this fix skips the revision.
> Fix issue when target ADO instance has no valid iteration path for a revision

- src/MigrationTools.Clients.AzureDevops.ObjectModel/Enrichers/TfsAttachmentEnricher.cs
This PR fixes the issue with duplicate attachment names reported in #923 by looking up existing attachments by name **and** size (not a perfect solution as an attachment with the same name and exact size will still fail to migrate, but that is a far more unlikely scenario)
> Improve handling for work item attachments with duplicate names

- src/VstsSyncMigrator.Core/Execution/MigrationContext/WorkItemMigrationContext.cs
The changes in this PR forward the configuration setting from the v1 processor (in the configuration.json file) to the ```WorkItemLinkEnricher```. Currently, I think ```LinkMigrationSaveEachAsAdded``` is not taken into account at all and the default value for ```FilterWorkItemsThatAlreadyExistInTarget``` hinders updates of WI links.
Please get back in case of questions and consider the merge!
(I haven't updated gitversion*.yml for the moment. Please give me the relevant hints.)
> configure WorkItemLinkEnricher

- README.md
- src/MigrationTools.Clients.AzureDevops.ObjectModel/Enrichers/TfsEmbededImagesEnricher.cs
In my case, when an HTML field contained more than one embedded image, only the last image was replaced correctly. By making the regex lazy instead of greedy, the problem was fixed.
Please test this carefully as I fixed this in another base version where we also used a capturing group for url replacement.
> Make embedded images regex lazy

- src/MigrationTools.Clients.AzureDevops.ObjectModel/ProcessorEnrichers/TfsNodeStructure.cs
Updated `TfsNodeStructure` to use `RegexOptions.IgnoreCase` so that Project name casing does not restrict usability!
> Updated `TfsNodeStructure` 

- src/MigrationTools.Clients.AzureDevops.ObjectModel/FieldMaps/FieldMergeMap.cs
The old code wouldn't account for fields with null values, but we need those to keep the right number of items in the list.
> Added support for null values to still be added to the sourceData list

- src/MigrationTools.Clients.AzureDevops.ObjectModel/ProcessorEnrichers/TfsNodeStructure.cs
If users forget to configure nodeBasePaths its not defaulting the value and resulting in unfriendly error messages.
I believe this was the case here in #1268 , #1239 
Just adding a little null check.
> Protect CheckIsParentOfSelectedBasePath against null nodeBasePaths

- src/MigrationTools/_EngineV1/Configuration/Processing/TestPlansAndSuitesMigrationConfig.cs
- src/VstsSyncMigrator.Core/Execution/MigrationContext/TestPlansAndSuitesMigrationContext.cs
> Update spelling of TestPlansAndSuitesMigrationContext

- src/MigrationTools.Host/MigrationToolHost.cs
- src/MigrationTools.Host/StartupService.cs
**Problem:**
The return code of  Migration.exe is always set to -1 even if a migration run is successful. If you want to incorporate the Migration.exe in a script, you should be able to base yourself on the exit code.
**Solution:**
Small fix ithat if the migration process is successful the return code is not modified aka 0. In the case of an error, the exit code should be set to a non zero value.
> exitcode=0 when no failures occur

- docs/Reference/Generated/MigrationTools.Clients.AzureDevops.Rest.xml
- src/MigrationTools.Clients.AzureDevops.Rest/Endpoints/AzureDevOpsEndpoint.cs
- src/MigrationTools.Clients.AzureDevops.Rest/Processors/AzureDevOpsPipelineProcessor.cs
- src/MigrationTools/DataContracts/Pipelines/Tasks.cs
This PR adds an additional filtering for Build Definitions and Task Groups. before trying to migrate them, a validation runs to ensure that all referenced tasks are actually available inside the target project.
If that is not the case, a warning will be generated and the pipeline processor will not further try to migrate the invalid definition(s).
This fixes part of #1460 
Example of how the output would look like:
> Extend Build Definition and Task Group filtering

- docs/getting-started.md
Fix an issue with the reference guide path in the getting started file. 
The reference guide path was incorrect and was leading to a 404 error page. 
This pull request updates the reference guide path to the correct URL.
> Fix Reference Guide path in getting started file

- src/MigrationTools.Clients.AzureDevops.ObjectModel/ProcessorEnrichers/TfsNodeStructure.cs
wrongly typed the iteration path in config:
"Something\\Sprint_history" - should be like that
"Something\\sprint_history" - was like that
that caused that while loop to reenter even tho pathSegments at line 184 were already empty.
> fixed empty Stack issue

- docs/Reference/v2/Endpoints/TfsWorkItemEndpoint-notes.md
- docs/Reference/v2/Endpoints/index.md
Correct Markdown tables display issues as they were not properly formatted, which made it difficult to read and understand.
These 2 files:
-  [TfsWorkItemEndpoint-notes](https://github.com/RehabAbotalep/azure-devops-migration-tools/blob/fix-broken-links/docs/Reference/v2/Endpoints/TfsWorkItemEndpoint-notes.md)
- [index](https://github.com/RehabAbotalep/azure-devops-migration-tools/blob/fix-broken-links/docs/Reference/v2/Endpoints/index.md)
> Correct Markdown tables display issues

- src/MigrationTools.Clients.AzureDevops.ObjectModel/ProcessorEnrichers/TfsNodeStructure.cs
New Debug loggin for @ejmarmonti
```
Log.LogDebug("NodeStructureEnricher.GetNewNodeName::Mappers", mappers);
foreach (var mapper in mappers)
{
Log.LogDebug("NodeStructureEnricher.GetNewNodeName::MapperToRun::{key}", mapper.Key);
if (Regex.IsMatch(sourceNodePath, mapper.Key, RegexOptions.IgnoreCase))
{
Log.LogDebug("NodeStructureEnricher.GetNewNodeName::MapperMatched::{key}", mapper.Key);
string replacement = Regex.Replace(sourceNodePath, mapper.Key, mapper.Value);
Log.LogDebug("NodeStructureEnricher.GetNewNodeName::MapperMatched::{key}::replaceWith({replace})", mapper.Key, replacement);
return replacement;
}
}
```
Added `MapperToRun`, `MapperMatched`, and `replaceWith` to help with debugging #1589
> Extra logging new node name

- configuration.json
- docs/Reference/Generated/MigrationTools.xml
- src/MigrationTools.Clients.AzureDevops.ObjectModel.Tests/Endpoints/TfsWorkItemEndPointTests.cs
- src/MigrationTools.Clients.AzureDevops.ObjectModel/Endpoints/TfsWorkItemConvertor.cs
- src/MigrationTools.Clients.AzureDevops.ObjectModel/ProcessorEnrichers/TfsNodeStructure.cs
- src/MigrationTools/DataContracts/NodeStructureMissingItem.cs
- src/MigrationTools/DataContracts/RevisionItem.cs
- src/MigrationTools/Tests/TestingConstants.cs
- src/MigrationTools/_EngineV1/Configuration/Processing/WorkItemMigrationConfig.cs
- src/VstsSyncMigrator.Core/Execution/MigrationContext/WorkItemMigrationContext.cs
When the nodes are checked, there are better outputs, and validation of the mappings.
If you have a mapping, it will not be listed as an invalid node.
I have also validated that this works with work items that have been moved between projects using the config below. 
```
{
"$type": "WorkItemMigrationConfig",
"Enabled": true,
"ReplayRevisions": true,
"PrefixProjectToNodes": false,
"UpdateCreatedDate": true,
"UpdateCreatedBy": true,
"WIQLQueryBit": "AND [System.WorkItemType] NOT IN ('Test Suite', 'Test Plan')",
"WIQLOrderBit": "[System.ChangedDate] desc",
"LinkMigration": true,
"AttachmentMigration": true,
"AttachmentWorkingPath": "c:\\temp\\WorkItemAttachmentWorkingFolder\\",
"FixHtmlAttachmentLinks": false,
"SkipToFinalRevisedWorkItemType": false,
"WorkItemCreateRetryLimit": 5, …
```
> This now checks and validated the Nodes in an easier to see format.

- src/MigrationTools.Host/MigrationTools.Host.csproj
- src/MigrationTools.Host/Services/DetectVersionService.cs
- src/MigrationTools.Host/StartupService.cs
Incorporate the new https://github.com/basicx-StrgV/WGet.NET/releases/tag/3.0.0 update into the check for version at the beginning of the application.
This incorporates https://github.com/basicx-StrgV/WGet.NET created by @basicx-StrgV to check that we are running the latest version at the beginning of the run.
> Added check for Winget version numbers

- src/MigrationTools.Host/Services/DetectVersionService2.cs
There is a glitch in the call for `IsNewLocalVersionAvailable` that returns true even when there is a match for versions.
> Fix for IsNewLocalVersionAvailable

- src/MigrationTools.Host/MigrationTools.Host.csproj
- src/MigrationTools.Host/Services/DetectVersionService.cs
- src/MigrationTools.Host/Services/DetectVersionService2.cs
With the newest version of `WGet.NET` (`3.2.0`) the check for the newest and current version of a package can be simplified.
Instat of checking for the correct package ID yourself, the `exact` flag can now be used.
Parsing of the version strings to a version object is also not needed anymore, because the `WinGetPackage` class now provides properties to get the parsed version object.
The new `WGet.NET` internal algorithm for passing version strings to a `Version` objects is able to parse version strings that can not be passed directly, as best as possible (e.g. Version strings like: `1.2.3-preview1` or  `1.2.3.1A2B3C`).
I have created this pull request which contains the possible improvements if you are interested in using them.
> Version check improvements

- docs/Reference/Generated/MigrationTools.Host.xml
- src/MigrationTools.Clients.AzureDevops.ObjectModel.Tests/MigrationTools.Clients.AzureDevops.ObjectModel.Tests.csproj
- src/MigrationTools.Clients.AzureDevops.Rest.Tests/MigrationTools.Clients.AzureDevops.Rest.Tests.csproj
- src/MigrationTools.Clients.AzureDevops.Rest/MigrationTools.Clients.AzureDevops.Rest.csproj
- src/MigrationTools.Clients.FileSystem.Tests/MigrationTools.Clients.FileSystem.Tests.csproj
- src/MigrationTools.Clients.InMemory.Tests/MigrationTools.Clients.InMemory.Tests.csproj
- src/MigrationTools.Host.Tests/MigrationTools.Host.Tests.csproj
- src/MigrationTools.Host/MigrationToolHost.cs
- src/MigrationTools.Host/MigrationTools.Host.csproj
- src/MigrationTools.Host/StartupService.cs
- src/MigrationTools.Integration.Tests/MigrationTools.Integration.Tests.csproj
- src/MigrationTools.Tests/MigrationTools.Tests.csproj
- src/MigrationTools/MigrationTools.csproj
- src/VstsSyncMigrator.Core.Tests/VstsSyncMigrator.Core.Tests.csproj
When showing the version number in the log file we want to be able to also show a version number when folks are debugging locally. I added https://github.com/devlooped/GitInfo from @devlooped to enable this.
We then add either the assembly version or the latest Git tag!
```
private static string GetVersionTextForLog()
{
Version runningVersion = DetectVersionService2.GetRunningVersion();
string textVersion = ((runningVersion.Major > 1) ? "$v" + runningVersion : ThisAssembly.Git.BaseTag.Replace("v", "") + "-local");
return textVersion;
}
```
This ensures that the version is shown on the log as either:
- Running locally in debug: `[18:20:56 DBG] [v14.2.1-2-local] Hosting starting`
- Running from Winget/Choco/portable: `[18:20:56 DBG] [v14.2.1] Hosting starting`
Either way, we can determine …
> Use GitVersion in the tool

- README.md
- docs/Reference/Generated/MigrationTools.Host.xml
- docs/_data/reference.v1.processors.workitemmigrationcontext.yaml
- docs/_data/reference.v2.processorenrichers.tfsnodestructure.yaml
- docs/collections/_reference/reference.v1.processors.workitemmigrationcontext.md
- docs/collections/_reference/reference.v2.processorenrichers.tfsnodestructure.md
- src/MigrationTools.Clients.AzureDevops.ObjectModel/ProcessorEnrichers/TfsNodeStructure.cs
- src/MigrationTools.Clients.AzureDevops.ObjectModel/ProcessorEnrichers/TfsNodeStructureOptions.cs
- src/MigrationTools.Host/MigrationToolHost.cs
- src/MigrationTools.Host/StartupService.cs
- src/MigrationTools/_EngineV1/Configuration/Processing/WorkItemMigrationConfig.cs
- src/VstsSyncMigrator.Core/Execution/MigrationContext/WorkItemMigrationContext.cs
Instead of creating all of the nodes at the start, we create them when we check the history instead.
This way all nodes can be mapped as needed, if needed.
https://github.com/nkdAgility/azure-devops-migration-tools/discussions/1727
[ ] TODO Add flag!
> Experiment: Create Nodes (Area\Iteration) at validation and not up front.

- docs/Reference/Generated/MigrationTools.Host.xml
- src/MigrationTools.Clients.AzureDevops.ObjectModel/Enrichers/TfsGitRepositoryEnricher.cs
- src/MigrationTools.Clients.AzureDevops.ObjectModel/ProcessorEnrichers/TfsNodeStructure.cs
- src/MigrationTools.Clients.AzureDevops.ObjectModel/_Enginev1/Clients/TfsMigrationClient.cs
- src/MigrationTools.Host/StartupService.cs
- src/MigrationTools/DataContracts/NodeStructureMissingItem.cs
- src/VstsSyncMigrator.Core/Execution/MigrationContext/WorkItemMigrationContext.cs
Bring out your Dead! 
1. Fix the update on the new version loop. It no longer does auto-update as Winget does not support it.
2. `skipToFinalRevisedWorkItemType` now works more how people expect by jumping to the final type, and then applying the mapping set in the config. This way a work item of the old type is never created. #1734 #1581
3. Add a full failure and exit if we fail to create a Source or Target Store. #1712 
4. This change should enable the tools on pre Git version of TFS. #1577
5. Updated the regex to allow for root nodes to ve valid so that they are checked as well. #1738 
**_What else?_**
> Clean Up on Aisle 4

- docs/Reference/Generated/MigrationTools.Host.xml
- src/VstsSyncMigrator.Core/Execution/MigrationContext/TestPlansAndSuitesMigrationContext.cs
Update to add additional logging and check for null reference when test plan does not match. Usually only happens when test plns have the same name!
Updates for #1770
> Additional Logging for `TestPlansAndSuitesMigrationContext` at `FindTestPlan`

- docs/Reference/Generated/MigrationTools.Host.xml
- src/VstsSyncMigrator.Core/Execution/MigrationContext/TestPlansAndSuitesMigrationContext.cs
Thank you for responding so quickly.
I still believe the behavior is incorrect. 
This line finds the target test Plan and sets it to the variable of `testPlan`
```csharp
ITestPlan testPlan = (from p in tmc.Project.TestPlans.Query("Select * From TestPlan") where p.Name == name select p).SingleOrDefault();
```
This line uses the ID of the target work item to find an item in source, thereby returning the wrong work item.
```csharp
var sourceWI = Engine.Source.WorkItems.GetWorkItem(testPlan.Id.ToString());
```
Observe how in my case the id of 12422 finds a Test Plan in the target, but a Bug work item in the source
_Originally posted by @sonofhammer in https://github.com/nkdAgility/azure-devops-migration-tools/discussions/1770#discussioncomment-7766304_
The fix is to pass in the …
> Update `FindTestPlan` to actually check the right things

- src/MigrationTools.Clients.AzureDevops.Rest/Endpoints/AzureDevOpsEndpoint.cs
For some reason, we have the User Agent hard coded on `AzureDevOpsEndpoint`. No idea why, but it looks like the version that's coded is no longer supported.
This comments out that line to hopefully resolve the issue some users are facing of `BrowserNotSupportedException`.
https://github.com/nkdAgility/azure-devops-migration-tools/discussions/1783
This closes #1784 1784
> Remove hard coded `user-agent` From `AzureDevOpsEndpoint`

- docs/Reference/Generated/MigrationTools.Host.xml
- src/VstsSyncMigrator.Core/Execution/MigrationContext/WorkItemMigrationContext.cs
Added a validator at the start of the migration process that:
1. Created a distinct list of all of the work item types used in each revision of the Source work items in scope
2. Create a list of the target work item types
3. Compare these lists to see if there are any types needed for the migration that is missing.
4. List all of the missing Work Item Types and if they are mapped
5. Throw and exit if any of the needed Types are missing and not mapped.
This should prevent folks from getting errors mid-execution if they were not aware of a work item type migration or of an old conversation and then subsequent deletion of the work item type. 
Resovles #1832 and contributes to resolving #1556
> Validation to check Work Item Type Defenitions

- src/VstsSyncMigrator.Core/Execution/MigrationContext/WorkItemMigrationContext.cs
Update `CheckClosedDateIsValid` to check both versions of the ClosedDate field and validate that they exist the same on the source and target process.
Fixes #1870, #1858, #1747
> Update `CheckClosedDateIsValid` to check both versions of the ClosedDate

- src/MigrationTools.Clients.AzureDevops.ObjectModel/ProcessorEnrichers/TfsWorkItemLinkEnricherOptions.cs
- src/VstsSyncMigrator.Core/Execution/MigrationContext/WorkItemMigrationContext.cs
This should truncate longTest fields to the max length and resolve #1861
> [Preview] Truncate LongText fields to 1m

- docs/Reference/v2/ProcessorEnrichers/TfsNodeStructure-notes.md
- src/MigrationTools.Clients.AzureDevops.ObjectModel/ProcessorEnrichers/TfsNodeStructure.cs
It looks like the follwoing was not clear and continues to result in support requests:
> There are 4 Nodes (Area or Iteration) found in the history of the Source that are missing from the Target! These MUST be added or mapped before we can continue using the instructions on
> https://nkdagility.com/learn/azure-devops-migration-tools/Reference/v1/Processors/WorkItemMigrationContext/#iteration-maps-and-area-maps
Trying with the following:
> !! There are MISSING Area or Iteration Paths"
> NOTE: It is NOT possible to migrate a work item if the Area or Iteration path does not exist on the target project. This is because the work item will be created with the same Area and Iteration path as the source work item with the project name swapped. The work item will not be created if the path does …
> [preview] Update to documenation and code to make 

- src/MigrationTools.Clients.AzureDevops.ObjectModel.Tests/ProcessorEnrichers/TfsRevisionManagerTests.cs
- src/MigrationTools.Clients.AzureDevops.ObjectModel/Endpoints/TfsWorkItemConvertor.cs
- src/MigrationTools.Clients.AzureDevops.ObjectModel/ProcessorEnrichers/TfsRevisionManager.cs
- src/MigrationTools/DataContracts/RevisionItem.cs
Fix for #1660
The new addition will check that all dates are consecutive with at least a full-second difference.
> [preview] Full fix for #1660 will ensure that all revisions have consecutive datetime with a full second intervel.

- src/MigrationTools.Clients.AzureDevops.ObjectModel.Tests/MigrationTools.Clients.AzureDevops.ObjectModel.Tests.csproj
- src/MigrationTools.Clients.AzureDevops.ObjectModel.Tests/ProcessorEnrichers/TfsRevisionManagerTests.cs
- src/MigrationTools.Clients.AzureDevops.ObjectModel/MigrationTools.Clients.AzureDevops.ObjectModel.csproj
- src/MigrationTools.Clients.AzureDevops.ObjectModel/ProcessorEnrichers/TfsRevisionManager.cs
- src/MigrationTools.Clients.AzureDevops.Rest/MigrationTools.Clients.AzureDevops.Rest.csproj
- src/MigrationTools.Integration.Tests/MigrationTools.Integration.Tests.csproj
- src/MigrationTools.TestExtensions/MigrationTools.TestExtensions.csproj
- src/MigrationTools/MigrationTools.csproj
- src/VstsSyncMigrator.Core/Execution/MigrationContext/WorkItemMigrationContext.cs
- src/VstsSyncMigrator.Core/VstsSyncMigrator.Core.csproj
Full update to the latest v19 version of the Azure DevOps API files as well as fix test implementation for revisions.
> [preview] Update/azure dev ops api 19

- src/MigrationTools.Clients.AzureDevops.ObjectModel/Processors/TfsTeamSettingsProcessor.cs
Run into issue migrating capacities when user display names were different in source and destination organizations - "John Doe" vs "Doe, John". This commit is trying to match users using different display name format combinations.
> Try to match users with different display name formats when migrating capacities

- src/MigrationTools.Clients.AzureDevops.ObjectModel/ProcessorEnrichers/TfsAttachmentEnricher.cs
The system ignored `TfsAttachmentEnricherOptions` and used empty variables instead. This fix removes the empty local variables and always uses the values in `TfsAttachmentEnricherOptions`
For Bug reported by @muradjames and will fix #2003
> [preview] Update to now use values from `TfsAttachmentEnricherOptions`

- src/MigrationTools.Clients.AzureDevops.ObjectModel/Enrichers/TfsEmbededImagesEnricher.cs
Fixes #2050 
The method Uri.ToString() fails to encode spaces as %20, leading to incorrect outcomes in URL comparisons. To address this, I have modified the code to use Uri.AbsoluteUri, which correctly encodes the URL. This change ensures that the comparison operates as expected in the following code snipped.
` if (!match.Value.ToLower().Contains(oldTfsurl.ToLower()) && !match.Value.ToLower().Contains(oldTfsurlOppositeSchema.ToLower()))
`
> [preview] Images Not Correctly Migrated from TFS Server URLs Containing Spaces

- .github/workflows/main.yml
While intended to be a fix for the Choco release, it seems that I also have an issue with the triggers.
> Fix for Choco, with some trigger changes as well

- .github/workflows/main.yml
🔧 (main.yml): update versioning scheme in packageExtension script
Switch the versioning scheme from `GitVersion_MajorMinorPatch` and `GitVersion_PreReleaseNumber` to `GitVersion_AssemblySemVer` for better alignment with semantic versioning practices. This change ensures that the versioning is more consistent and easier to manage.
> Update Marketplace Package to better version number

- docs/Reference/Generated/MigrationTools.xml
- src/MigrationTools/MigrationTools.csproj
- src/MigrationTools/Services/TelemetryClientAdapter.cs
✨ (MigrationTools): integrate GitInfo package for versioning and repository metadata
📝 (MigrationTools): update MigrationTools.xml with GitInfo fields
🔧 (MigrationTools.csproj): add GitInfo package reference
♻️ (TelemetryClientAdapter): update versioning logic to use GitInfo
Integrate the GitInfo package to automatically include repository metadata such as branch, commit, and version information. This enhances the application's ability to provide detailed versioning and repository state information, which is crucial for debugging and traceability. The MigrationTools.xml documentation is updated to reflect the new fields provided by GitInfo. The TelemetryClientAdapter is refactored to use GitInfo for generating version strings, improving accuracy and consistency in version reporting.
> ✨📝 🔧♻️ Integrate better version number detection for local runs

- src/MigrationTools.Host/MigrationToolHost.cs
✨ (MigrationToolHost.cs): add singleton services for migration tool version info and version
Adding `IMigrationToolVersionInfo` and `IMigrationToolVersion` as singleton services ensures that these instances are shared across the application, improving efficiency and consistency in accessing version information.
> Missing services

- docs/Reference/Generated/MigrationTools.xml
- src/MigrationTools.Clients.AzureDevops.ObjectModel/ProcessorEnrichers/TfsAttachmentEnricher.cs
- src/MigrationTools.Clients.AzureDevops.ObjectModel/ProcessorEnrichers/TfsNodeStructure.cs
- src/MigrationTools.Host/Commands/CommandBase.cs
- src/MigrationTools.Host/Commands/ExecuteMigrationCommand.cs
- src/MigrationTools.Host/MigrationToolHost.cs
- src/MigrationTools.Host/StartupService.cs
This PR should remove some common user errors from the logging.
> Removing some Error meesages that are user based

- src/MigrationTools.Clients.AzureDevops.ObjectModel/Endpoints/TfsWorkItemConvertor.cs
- src/VstsSyncMigrator.Core/Execution/MigrationContext/WorkItemMigrationContext.cs
🐛 (TfsWorkItemConvertor.cs): fix logging issue by removing exception parameter from Log.Warning
The exception parameter `e` is removed from the `Log.Warning` call because it is not used in the log message. This change ensures that the log message correctly reflects the intended warning without unnecessary information.
> Error in TfsWorkItemConvertor and Null reference in WorkItemMigrationContext

- src/VstsSyncMigrator.Core/Execution/MigrationContext/WorkItemMigrationContext.cs
🐛 (WorkItemMigrationContext.cs): fix variable name from _config.WIQLQuery to targetWIQLQuery
The variable name _config.WIQLQuery is incorrect and should be targetWIQLQuery to match the intended logic and improve code readability. This change ensures that the correct query is used for filtering existing work items, preventing potential migration issues.
Fixes: #2232
> [Bug]: Target Query not Used

- .github/labeler.yml
🔧 (labeler.yml): correct typo in labeler configuration
Fixes a typo in the labeler configuration file. The key `all-glob-to-any-file` is corrected to `all-globs-to-any-file` to ensure proper functionality of the labeler. This change ensures that the labeler correctly identifies changes in the `src` directory for the `enhancement` label.
> all-globs-to-any-file

- .github/labeler.yml
🔧 (labeler.yml): correct typo in labeler configuration
Fixes a typo in the labeler configuration file to ensure proper functionality. The key 'all-globs-to-any-files' is corrected to 'all-globs-to-any-file' to match the expected syntax and avoid potential misconfigurations.
> all-globs-to-any-files

- docs/Reference/Generated/MigrationTools.xml
- src/MigrationTools.Clients.AzureDevops.ObjectModel/Enrichers/TfsWorkItemEmbededLinkEnricher.cs
- src/MigrationTools.Clients.AzureDevops.ObjectModel/_Enginev1/Clients/TfsWorkItemMigrationClient.cs
- src/MigrationTools.Tests/Core/Clients/WorkItemMigrationClientMock.cs
- src/MigrationTools/_EngineV1/Clients/IWorkItemMigrationClient.cs
- src/MigrationTools/_EngineV1/Clients/WorkItemMigrationClientBase.cs
♻️ (MigrationTools): refactor GetWorkItem method to include stopOnError parameter
The GetWorkItem method now includes an optional stopOnError parameter, which defaults to true. This change allows for more flexible error handling by enabling the caller to decide whether the application should exit on error or continue execution. This is particularly useful for scenarios where non-critical errors should not halt the entire migration process. Additionally, updated the corresponding tests and interfaces to accommodate this new parameter.
> Fix error on Embeded Link for Work item that does not exist.

- build/include/Get-ReleaseDescription.ps1
- build/include/test.ps1
- docs/Reference/Generated/MigrationTools.xml
♻️ (Get-ReleaseDescription.ps1): refactor to use Get-GitChanges function for better modularity
Refactor the script to replace inline git operations with a call to the Get-GitChanges function. This improves code modularity and readability, making it easier to maintain and extend in the future. The new function encapsulates the logic for fetching git changes based on the specified mode, reducing redundancy and potential errors.
✨ (Get-ReleaseDescription.ps1): add new function Get-ReleaseDescription2 for enhanced release descriptions
♻️ (Get-ReleaseDescription.ps1): refactor existing functions to improve modularity and readability
🔧 (Get-ReleaseDescription.ps1): add new configuration options for OpenAI API integration
Introduce a new function `Get-ReleaseDescription2` to generate detailed …
> ♻️ Refactor Get-ReleaseDescription.ps1 to Improve Modularity and Add Enhanced Release Description Functionality

- src/MigrationTools.Clients.AzureDevops.ObjectModel/_Enginev1/Clients/TfsMigrationClient.cs
✨ (TfsMigrationClient.cs): add support for VssClientCredentials in Prompt authentication mode
Import the `Microsoft.VisualStudio.Services.Client` namespace and use `VssClientCredentials` with `PromptIfNeeded` to enhance the authentication process. This change ensures that credentials are prompted only when necessary, improving user experience and security.
!reported by @v-prvusi999
Discussed in #2303
Closes #2307
> [Fix] Prompt for Credentails

- .github/workflows/main.yml
The trailing slash is removed from the `docs_baseURL` to ensure consistency in URL formatting and to prevent potential issues with URL resolution in the documentation deployment process.
> 🔧 (main.yml): remove trailing slash from docs_baseURL for consistency

- docs/Reference/Generated/MigrationTools.xml
- src/MigrationTools.Host/Commands/ExecuteMigrationCommand.cs
- src/MigrationTools.Host/MigrationToolHost.cs
- src/MigrationTools/MigrationTools.csproj
- src/MigrationTools/Processors/Infrastructure/InvalidProcessorException.cs
- src/MigrationTools/Processors/Infrastructure/ProcessorContainerOptions.cs
Checking the Elmah.io logs for exceptions.
> Update Exceptions for v16

- .github/workflows/main.yml
- build/packageExecutable.ps1
- docs/Reference/Generated/MigrationTools.xml
- src/MigrationTools.ConsoleFull/MigrationTools.ConsoleFull.csproj
Update to check where these missing files are!
> WITDataStore64 files missing! 

- docs/Reference/Generated/MigrationTools.xml
- src/MigrationTools.Clients.TfsObjectModel/Tools/TfsNodeStructureToolOptions.cs
- src/MigrationTools.ConsoleFull/Properties/launchSettings.json
- src/MigrationTools/Endpoints/Infrastructure/EndpointRegistrationExtensions.cs
- src/MigrationTools/Options/OptionsConfigurationUpgrader.cs
The TfsNodeStructureTool mappings were not comming across as we have changes the format. Ive added a custom mapped to get the data on upgrade.
> Added custom mapping for new format in TfsNodeStructureTool

- docs/Reference/Generated/MigrationTools.xml
- docs/getstarted/index.md
- docs/setup/permissions.md
- src/MigrationTools/Endpoints/Infrastructure/EndpointRegistrationExtensions.cs
- src/MigrationTools/Endpoints/Infrastructure/IEndpointOptions.cs
- Update links to "install" in Getting Started
- Update the permissions page to be more consistent and readable on permissions.
- Fix for #2361 reported by @fgudelj1 in #2360
> Niggles v16 (Docs) + Bugs

- configuration.json
- docs/Reference/Generated/MigrationTools.xml
- src/MigrationTools.Clients.TfsObjectModel.Tests/Processors/TfsWorkItemMigrationProcessorTests.cs
- src/MigrationTools.Clients.TfsObjectModel.Tests/ServiceProviderHelper.cs
- src/MigrationTools.Clients.TfsObjectModel/EndPoints/Infrastructure/TfsTeamProjectAuthentication.cs
- src/MigrationTools.Clients.TfsObjectModel/Endpoints/TfsEndpointOptions.cs
- src/MigrationTools.Clients.TfsObjectModel/Endpoints/TfsLanguageMapOptions.cs
- src/MigrationTools.Clients.TfsObjectModel/Processors/Infra/TfsProcessor.cs
- src/MigrationTools.Clients.TfsObjectModel/Processors/TfsWorkItemMigrationProcessorOptions.cs
- src/MigrationTools.Clients.TfsObjectModel/Processors/TfsWorkItemMigrationProcessorOptionsValidator.cs
- src/MigrationTools.Clients.TfsObjectModel/ServiceCollectionExtensions.cs
- src/MigrationTools/Endpoints/Infrastructure/EndpointRegistrationExtensions.cs
- src/MigrationTools/Exceptions/ConfigurationValidationException.cs
- src/MigrationTools/Options/NetworkCredentialsOptions.cs
- src/MigrationTools/Processors/Infrastructure/Processor.cs
- src/MigrationTools/Processors/Infrastructure/ProcessorOptions.cs
Both @soodgautam and @nkofctg ran into issues with the `when you are migrating to Azure DevOps you MUST provide an PAT so that we can call the REST API for certain actions. For example, we would be unable to deal with a Work item Type change.` message! 
This was due to the `SourceName` and/or `TargetName` on the Processor being set to null. The validator now checks for this!
It now checks for:
> Improve validation for TfsEndpoint PAT tokens and message

- docs/Reference/Generated/MigrationTools.xml
- src/MigrationTools.Clients.TfsObjectModel/Tools/TfsNodeStructureTool.cs
📝 (MigrationTools.xml): update documentation to reflect latest git metadata
💡 (TfsNodeStructureTool.cs): add warning log when node structure enricher is disabled
The documentation is updated to reflect the latest git metadata, including branch, commit, SHA, commit date, and versioning information. This ensures that the documentation is accurate and up-to-date.
A warning log is added to `TfsNodeStructureTool.cs` to notify users when the node structure enricher is disabled. This helps in debugging and ensures users are aware of potential migration errors due to the disabled state.
> add warning log when node structure enricher is disabled

- .github/workflows/main.yml
🔧 (main.yml): add AzureSitesEnvironment variable and GitHub App token for deployment
Introduce the AzureSitesEnvironment variable to manage different deployment environments (e.g., preview, canary). This change allows for more flexible and environment-specific deployments. Additionally, add steps to create a GitHub App token and use it for deploying static web apps to Azure, enhancing security and automation in the deployment process.
> Update to also publish to Azure Static Sites

- docs/Reference/Generated/MigrationTools.xml
- src/MigrationTools.Host/Commands/CommandBase.cs
- src/MigrationTools.Host/MigrationToolHost.cs
- src/MigrationTools/Services/LogLocationService.cs
- change the rolling interval on the main log to hourly, and to rollOnFileSizeLimit
- change the rolling interval on the error log to daily
- Added the log path to the output, beginning and end.
> 🔧  centralize log path creation and improve logging

- src/MigrationTools.Clients.TfsObjectModel/Endpoints/TfsEndpointOptions.cs
The previous implementation used `Uri.IsWellFormedUriString` which is less robust. The new implementation uses `Uri.TryCreate` to ensure the Collection property is a valid URL, providing more accurate validation and error handling. This change enhances the reliability of the URL validation process.
> 🐛 (TfsEndpointOptions.cs): improve URL validation logic for Collection property

- configuration.json
- docs/Reference/Generated/MigrationTools.xml
- src/MigrationTools.Clients.TfsObjectModel/Tools/TfsUserMappingTool.cs
🔧 (configuration.json): add TfsUserMappingTool configuration for user mapping
💡 (TfsUserMappingTool.cs): improve error handling for missing user mapping file
📝 (MigrationTools.xml): update documentation with new version details
The TfsUserMappingTool configuration is added to the configuration.json to enable user mapping functionality, specifying the file path and identity fields to check. This change allows for more flexible user identity management during migrations. In TfsUserMappingTool.cs, error handling is improved by logging an error message when the user mapping file is missing, ensuring users are informed of configuration issues. The MigrationTools.xml documentation is updated to reflect the new version, ensuring consistency and clarity in version tracking.
> User mapping logic error

- configuration.json
- docs/Reference/Generated/MigrationTools.xml
- src/MigrationTools.Clients.TfsObjectModel/Tools/TfsNodeStructureTool.cs
- src/MigrationTools/Exceptions/MigrationToolsException.cs
- src/MigrationTools/Processors/Infrastructure/Processor.cs
Add new exception type that allows use to determine if it is a loggable error better....
For #2414 I also added validation for the Target Project name before trying to load the Area or Iteration nodes....
> Exception enhancement

- docs/Reference/Generated/MigrationTools.xml
- src/MigrationTools.Clients.TfsObjectModel/Tools/TfsNodeStructureTool.cs
- src/MigrationTools/Exceptions/MigrationToolsException.cs
♻️ (MigrationTools): refactor exception handling and update XML references
Update the XML documentation to reflect the latest commit and tag information, ensuring that the documentation remains accurate and up-to-date. This change is necessary to maintain consistency with the current state of the codebase.
Refactor exception handling in `TfsNodeStructureTool.cs` by introducing an extension method `AsMigrationToolsException`. This improves code readability and reduces redundancy by centralizing the conversion of exceptions to `MigrationToolsException`. The refactoring also removes unused imports and redundant code, streamlining the codebase for better maintainability.
Should fix #2406
>  refactor exception handling and update XML references

- src/MigrationTools.Clients.TfsObjectModel/Tools/TfsGitRepositoryTool.cs
- src/MigrationTools.Clients.TfsObjectModel/Tools/TfsGitRepositoryToolOptions.cs
- src/MigrationTools.Clients.TfsObjectModel/Tools/TfsGitRepositoryToolOptionsValidator.cs
✨ (TfsGitRepositoryTool): add validation and logging for TfsGitRepositoryTool options
Add a check to ensure the TfsGitRepositoryEnricher is enabled before proceeding, logging a warning if it is not. This prevents unnecessary operations when the feature is disabled. Introduce a default initialization for the Mappings dictionary to avoid null references. Implement a new options validator class, TfsGitRepositoryToolOptionsValidator, to ensure that Mappings is always initialized, enhancing robustness and preventing runtime errors. These changes improve the reliability and maintainability of the tool by ensuring proper configuration and logging.
Closes #2410
> Validator for TfsGitRepositoryTool and honor the enabled:false

- .github/workflows/labeler.yml
- .github/workflows/main.yml
🔧 (workflows): update GitHub Actions workflows for improved PR handling
Comment out the labeler workflow to temporarily disable it, possibly for debugging or performance reasons. Modify the main workflow to use `pull_request_target` instead of `pull_request` for better security and add specific event types to trigger the workflow. Introduce conditional logic to ensure the workflow only runs under safe conditions, such as when a PR is labeled 'safe-to-build'. Add steps to remove the 'safe-to-build' label from PRs originating from forks, ensuring that only trusted code is built. Update the checkout steps to handle both push and pull request events correctly, ensuring the correct repository and ref are checked out. These changes enhance the security and flexibility of the CI/CD pipeline by …
> Update workflow to protextfrom but run external PRs

- .github/workflows/close-pr.yaml
- .github/workflows/main.yml
🔧 (close-pr.yaml): add condition to skip workflow for forked repositories
Add a conditional check to ensure the workflow only runs on pull requests from the main repository, not from forks. This prevents unnecessary execution of the workflow on forked repositories, optimizing resource usage and maintaining focus on relevant pull requests.
> 🔧 (close-pr.yaml): Add condition to skip workflow for forked repositories to optimize resource usage

- src/MigrationTools.Clients.TfsObjectModel/Processors/TfsWorkItemMigrationProcessor.cs
Some work items do not have this field...
Updated to:
```
if (newWorkItem.Fields.Contains("Microsoft.VSTS.Common.ClosedDate") && newWorkItem.Fields["Microsoft.VSTS.Common.ClosedDate"].IsEditable)
{
newWorkItem.Fields["Microsoft.VSTS.Common.ClosedDate"].Value = oldWorkItem.Fields["Microsoft.VSTS.Common.ClosedDate"].Value;
}
```
Related Disucssions:
- https://github.com/nkdAgility/azure-devops-migration-tools/discussions/2086
-
> TF26027: A field definition Microsoft.VSTS.Common.ClosedDate in the work item type definition file does not exist. 

- src/MigrationTools/Services/ActivitySourceProvider.cs
♻️ (ActivitySourceProvider.cs): comment out OpenTelemetry tracing and logging configuration
The OpenTelemetry tracing and logging configuration is commented out to temporarily disable these features. This change is likely made to troubleshoot or isolate issues related to telemetry or to reduce overhead during development. The code is preserved for easy reactivation when needed.
> Remove Trace and Log from Open Telemitery

- .github/workflows/main.yml
🔧 (main.yml): add support for AFD base URL in GitHub Actions workflow
Introduce a new environment variable `nkdAgility_DocsBaseURL_AFD` to support Azure Front Door (AFD) base URLs in the GitHub Actions workflow. This change allows the workflow to handle different base URLs for documentation deployment, enhancing flexibility and compatibility with AFD configurations. The update ensures that the Jekyll build process uses the correct base URL for AFD, improving deployment accuracy.
> Support Azure Front Door (AFD)

- .github/workflows/MigrationToolsTelemetery.yml
- .github/workflows/main.yml
- .github/workflows/stale.yml
- docs/index.md
Update the "Getting Started" link to point directly to the index.md file for better navigation. Remove the redundant "How To Migrate Things" link to streamline the documentation. Correct the preview documentation URL to ensure users are directed to the correct preview site. These changes improve the accuracy and usability of the documentation.
> 📝 (index.md): update documentation links and correct preview URL

- src/MigrationTools.Clients.TfsObjectModel/Processors/TfsExportUsersForMappingProcessor.cs
- src/MigrationTools.Clients.TfsObjectModel/Tools/TfsUserMappingTool.cs
- src/MigrationTools/DataContracts/IdentityItemData.cs
`TfsUserMappingTool` is not working correctly in our scenario, which is:
- As our source server, we have on-premise TFS 2018 connected to on-premise Active Directory.
- As our target server, we have Azure DevOps connected to Azure Entra ID (formerly Azure Active Directory).
`TfsUserMappingTool` is not working at all, because **it will not load any user** from our on-premise TFS server. The problem is this part:
```cs
var people = SIDS.Members.ToList().Where(x => x.Contains("\\")).Select(x => x);
```
It processes only users, whose SID contains `\` character. But none of our users in TFS contains this. All data in `SIDS.Members` are SIDs of some kind of identity and we need to process them all. So the new logic is this:
- All SIDs are processed, so identity for every one of them is …
> TfsUserMappingTool: fix loading users from TFS connected to Active Directory

- Directory.Packages.props
- src/MigrationTools.Clients.TfsObjectModel/MigrationTools.Clients.TfsObjectModel.csproj
- src/MigrationTools.Clients.TfsObjectModel/Processors/TfsExportUsersForMappingProcessor.cs
- src/MigrationTools.Clients.TfsObjectModel/Tools/TfsUserMappingTool.cs
- src/MigrationTools.Clients.TfsObjectModel/Tools/TfsUserMappingToolOptions.cs
- src/MigrationTools/DataContracts/IdentityItemData.cs
Our scenario is:
- Source server is on-premise TFS 2018 connected to on-premise Active Directory.
- Target server is Azure DevOps connected to Azure Entra ID (formerly Azure Active Directory).
Even when the users are synchronized between the Active Directiories, the users' display names are often different between the two. So default matchind by display name does not work for us. I implemented the possibility to match users by email (at least for us it works for most cases). This matching is turned off by default. When turned on, it has higher precedence than matching by display name. So first, match by email is looked for and if no match is found, default matching by display name is used.
Because of this I expanded properties of the users loaded from server. I still do not use all of …
> TfsExportUsersForMappingProcessor: allow matching users by email

- src/MigrationTools.Clients.TfsObjectModel/Processors/TfsExportUsersForMappingProcessor.cs
- src/MigrationTools.Clients.TfsObjectModel/Processors/TfsExportUsersForMappingProcessorOptions.cs
- src/MigrationTools.Clients.TfsObjectModel/Processors/TfsWorkItemMigrationProcessor.cs
- src/MigrationTools.Clients.TfsObjectModel/Tools/TfsUserMappingTool.cs
- src/MigrationTools/DataContracts/IdentityItemData.cs
Our scenario is:
- Source server is on-premise TFS 2018 connected to on-premise Active Directory.
- Target server is Azure DevOps connected to Azure Entra ID (formerly Azure Active Directory).
Even when the users are synchronized between the Active Directiories, the users' display names are often different and also quite a bunch of email addresses are different. So a lot of people are not matched at all and in exported mapping file, the target name is `null`. So the mapping file needs to be manually edited to add missing users. Usually (almost always), the user is in target server, but has different email and display name. To help find the corresponding user, this PR allows to export all users in source and target server into separate JSON. We can than find the user we need and use his …
> TfsExportUsersForMappingProcessor: export all users in source and target server to JSON file

- src/MigrationTools.Clients.TfsObjectModel/Processors/TfsExportUsersForMappingProcessor.cs
- src/MigrationTools.Clients.TfsObjectModel/Tools/TfsUserMappingTool.cs
User mapping was defined in `TfsUserMappingTool._UserMappings` _private_ field and used only in one place by `TfsUserMappingTool.MapUserIdentityField` method. I believe, that user mapping can be used in some other places, for example users are loaded when migrating team backlog capacities. Now it triggers a lot of warning for us, because users in source are not the same as users in target. So I want to use user mapping also in this case. (I do not know yet, but maybe there are more places where user mapping can be used.)
So this PR makes public property `TfsUserMappingTool.UserMappings` as a lazy dictionary, that can be used later anywhere.
During this, I noticed a bug, which means, that probably no-one is using user mappings. The problem is, that user mapping JSON file was generated in …
> TfsUserMappingTool: make user map public, fix user mapping (de)serialization

- src/MigrationTools.Clients.TfsObjectModel/ServiceCollectionExtensions.cs
- src/MigrationTools.Clients.TfsObjectModel/Tools/TfsGitRepositoryTool.cs
Fix #2521 reported by @nirkal \n\n ✨ (ServiceCollectionExtensions.cs, TfsGitRepositoryTool.cs): add TfsChangeSetMappingTool to service collection and ensure required service retrieval
Add `TfsChangeSetMappingTool` to the service collection to enable its configuration and usage within the application. Change the retrieval method of `TfsChangeSetMappingTool` from `GetService` to `GetRequiredService` to ensure that the service is available and to prevent potential null reference exceptions. This change enhances the robustness and configurability of the application by ensuring necessary services are properly registered and retrieved.
> Bug in Chaneset Mapping

- src/MigrationTools.Clients.TfsObjectModel/Processors/TfsWorkItemMigrationProcessor.cs
- src/MigrationTools.Shadows/Tools/MockStringManipulatorTool.cs
- src/MigrationTools.Tests/ProcessorEnrichers/StringManipulatorEnricherTests.cs
- src/MigrationTools/Tools/Interfaces/IStringManipulatorTool.cs
- src/MigrationTools/Tools/StringManipulatorTool.cs
This should fix #2538
As mention id that bug report, custom user mapping is not applied during migration. @LudekStipal pointed to the code it was responsible for this. The problem is not the `StringManipulatorTool` itself, but the value which is used in that branch of code. The user mapping and all the other field mapping is done using `oldWorkItem` object, which is of type `Field`. But that specific branch for strings was processed using `oldWorkItemData` object which is of type `FieldItem`. So **it is the different object** and for user fields, it is not working with mapped user names, because the are mapped in the other place.
This is at least a bug for user fields which are mapped as @LudekStipal found. But I think, that is is also a potential source of bugs in the future, if …
> Refactor StringManipulator tool so it works just with string and not work item field

- .github/ISSUE_TEMPLATE/bug.yml
- .github/PULL_REQUEST_TEMPLATE/default.md
- _config.yml
- docs/Reference/FieldMaps/index.md
- docs/Reference/ProcessorEnrichers/index.md
- docs/Reference/Processors/TfsTestPlansAndSuitesMigrationProcessor-notes.md
- docs/Reference/Processors/TfsWorkItemMigrationProcessor-notes.md
- docs/Reference/Processors/index2.md
- docs/Reference/Tools/TfsNodeStructureTool-notes.md
- docs/collections/_faq/work-item-is-not-ready-to-save.md
- docs/collections/_howto/migrating-plans-and-suites.md
- docs/collections/_howto/user-mappings.md
- docs/getstarted/index.md
- docs/index.md
- docs/setup/reflectedworkitemid.md
- docs/version-control.md
I have been using these tools extensively recently and noticed a number of typos and other inconsistencies across the documentation, which I've taken some time to fix for you. Hope that's ok!
> Fix documentation issues (mostly typos)

- src/MigrationTools.Clients.TfsObjectModel/Tools/TfsEmbededImagesTool.cs
🐛 (TfsEmbededImagesTool.cs): improve error handling and logging for dummy work item creation
Add exception handling to provide more informative error messages when exceptions occur. Enhance logging to warn about invalid fields in the dummy work item and ensure that the work item is ready to save. This change helps in diagnosing issues related to work item creation by providing detailed logs and throwing exceptions when the dummy work item cannot be created due to save failures.
Fix for #2589 (or at least visibility) created by @anderssonpof
> Issue with TfsEmbededImagesTool and Rules

- src/MigrationTools.Clients.TfsObjectModel/Processors/TfsTestPlansAndSuitesMigrationProcessor.cs
🐛 (TfsTestPlansAndSuitesMigrationProcessor.cs): handle duplicate test plan names
Enhance the `FindTestPlan` method to handle scenarios where multiple test plans have the same name. Previously, the code assumed that test plan names were unique, which could lead to unexpected behavior or errors if duplicates existed. The updated logic checks for multiple test plans with the same name, logs a warning with their IDs, and throws an exception to prevent further execution. This ensures that the migration process does not proceed with ambiguous test plan identification, maintaining data integrity.
> Duplicate test Plan Names message update

- src/MigrationTools.Clients.TfsObjectModel/Processors/TfsTestPlansAndSuitesMigrationProcessor.cs
🐛 (TfsTestPlansAndSuitesMigrationProcessor.cs): fix potential index out of range error by using FirstOrDefault
The change from accessing the first element of the testPlans list directly to using FirstOrDefault prevents a potential IndexOutOfRangeException. This ensures that if the list is empty, the testPlan variable will be set to null instead of causing an error, improving the robustness of the code.
> Fix for Index Issue

- src/MigrationTools.Clients.TfsObjectModel/Processors/TfsWorkItemMigrationProcessor.cs
Handle case where there is no closed date field in target workitem. For us it didn't work for Shared parameter. We cannot modify shared parameter workitem in azure devops. Skip field didn't work.
> Skip closedDate field validation when closedDate field doesn't exist

- docs/Reference/index.md
Corrects several typos in the documentation to improve readability and understanding. The command `devlopsmigration` is corrected to `devopsmigration` to ensure users can execute the command successfully. Additionally, minor spelling errors are fixed to enhance the overall quality of the documentation.
From #2650
> 📝 (index.md): correct typos in documentation for clarity

- src/MigrationTools.Clients.TfsObjectModel/Processors/TfsTestPlansAndSuitesMigrationProcessor.cs
- src/MigrationTools.Clients.TfsObjectModel/Processors/TfsTestPlansAndSuitesMigrationProcessorOptions.cs
This flag filters all test plans and retains only the specified ones for migration. Pass the test plan IDs as an array. Example: "TestPlanIds": [123, 456, 789] . Works optimally when "TestPlanQuery" is set to null.
Idea link - https://github.com/nkdAgility/azure-devops-migration-tools/discussions/2648
> New flag in Test Plan config "TestPlanIds"

- src/MigrationTools.Clients.TfsObjectModel/Processors/TfsWorkItemMigrationProcessor.cs
**FEATURE SUGGESTION**
This PR adds a try-catch block around the line of code that tries to access the `Microsoft.VSTS.TCM.Steps` field, whcih can fail if the Steps field does not exist on the source work item.
This change has enabled us to map non-Test Case Work Item types to Test Cases, which was previously not possible.
I am submitting this PR in order to raise awareness of the issue. It seems like there are several unchecked attempts to access fields in the `oldWorkItemData` based on the available fields of `newWorkItemData`, without considering if those fields are present on the source work item or not.
The same thing happens for `Microsoft.VSTS.Common.Priority` here, and I can imagine that this will cause the same error if the source Work Item Types does not have the Priority field: …
> Log a warning if the Microsoft.VSTS.TCM.Steps field does not exist on the source work item.

- src/MigrationTools.Clients.TfsObjectModel/Processors/TfsWorkItemMigrationProcessor.cs
- src/MigrationTools.Clients.TfsObjectModel/Processors/TfsWorkItemMigrationProcessorOptions.cs
- src/MigrationTools.Clients.TfsObjectModel/Tools/TfsUserMappingToolOptions.cs
cause uservalidation need mutch time and when create a mapping file before it is not needed. with this option it can be skipped
> SkipValidateAllUsersExistOrAreMapped can be skippt over options

- src/MigrationTools.Clients.TfsObjectModel/Tools/FieldMappingTool/FieldMaps/MultiValueConditionalMap.cs
Fix for typecast error if work item field type is not a string (e.g., integer) in fieldmap multivalueconditionalmap -> "Field map fault System.InvalidCastException: Unable to cast object of type 'System.Int32' to type 'System.String'."
> Fix invalidcastexception in multivalueconditionalmap

- src/MigrationTools.Clients.TfsObjectModel/Processors/TfsWorkItemMigrationProcessor.cs
A have already fixed this in PR #2706 but it was broken (basically reverted) back in #2712. Now the processing of 10 000 items says, it will finish in 4 minutes and this time rapidly decreases – after processing 1000 items, the remainig time is only only 1 minute.
There are two main problems.
The duration of activity is not measured, but set to fixed time of 10 seconds using `activity?.SetEndTime(activity.StartTimeUtc.AddSeconds(10));`. I assume, that you did it because the `Duration` was zero when you accessed it when calculating `average`. This is because the `Duration` is not dynamic – it will not retur actual duration of activity. It is possible to set it directly to some fixed time with `SetEndTime`. But in our case when we need real duration of activity, we must stop it. When …
> Fix measuring time during work item migration

- CONTRIBUTING.md
- README.md
- _config.yml
- docs/_includes/header.html
- docs/_layouts/default.html
- docs/index.md
- docs/setup/installation.md
- src/MigrationTools.Chocolatey/nkdAgility.AzureDevOpsMigrationTools-Preview.nuspec
- src/MigrationTools.Clients.TfsObjectModel/EndPoints/Infrastructure/TfsTeamProjectAuthentication.cs
- src/MigrationTools.Clients.TfsObjectModel/Endpoints/TfsEndpointOptions.cs
- src/MigrationTools.Clients.TfsObjectModel/Endpoints/TfsTeamProjectEndpoint.cs
- src/MigrationTools.Clients.TfsObjectModel/Tools/TfsNodeStructureTool.cs
- src/MigrationTools.Extension/README.md
- src/MigrationTools.Extension/vss-extension.json
- src/MigrationTools.Host/Commands/ExecuteMigrationCommand.cs
📝 (docs): update documentation links to new domain
Update all documentation links from `nkdagility.com` to the new domain `devopsmigration.io`. This change ensures that users are directed to the correct and updated documentation site, improving accessibility and user experience. The update affects various markdown files, configuration files, and source code comments where documentation links are referenced.
> Move Docs to https://devopsmigration.io/

- docs/content/docs/config-wizard.md
- docs/hugo.preview.yaml
- docs/hugo.yaml
This pull request introduces updates to the documentation configuration and feature toggles for the Azure DevOps Migration Tools. The most important changes include adding cascading build rules for the configuration wizard documentation, enabling the configuration wizard feature in the preview environment, and modifying the feature toggle for the configuration wizard in the main configuration.
* [`docs/content/docs/config-wizard.md`](diffhunk://#diff-74164cb9cb5878eb6e196e138531baf584c1f086ed8862941457d32556107e0dR12-R17): Added cascading build rules to exclude the configuration wizard documentation from being listed or rendered in the production environment.
* [`docs/hugo.preview.yaml`](diffhunk://#diff-5b2bc656cefcb3f25cd9717a7a67c9c716a2fd4637ed5495b4add056d8fe71a7R7-R10): Enabled the …
> Fix feature flag

- src/MigrationTools.Clients.TfsObjectModel/Tools/TfsEmbededImagesTool.cs
Updated the logic for setting the `Authorization` header in `HttpClient` to improve security and flexibility. The code now checks if the `sourcePersonalAccessToken` is not empty and if the `matchedSourceUri` contains "tfs/DefaultCollection". If both conditions are met, the token is encoded in Base64 with an empty username; otherwise, the token is set directly if it's not empty.
> fix: Auth header when downloading images from tfs

- src/MigrationTools.Clients.TfsObjectModel/Tools/TfsEmbededImagesTool.cs
In #2853 I fixed downloading embedded images when connected to server by username/password. With this I broke when client is connected with PAT. @luxdave tried to fix it in #2877, but again broke connection with username/password.
This should fix everything. Authorization header si correctly generated for both cases:
- If the client is connected with username and password, it is created as `Base64("{username}:{password}")`.
- If the client is connected with PAT, it is created as `Base64(":{pat}")`.
> Fix authorization header when downloading embedded images with PAT

- appsettings.json
- docs/data/classes/reference.endpoints.tfsendpoint.yaml
- docs/data/classes/reference.endpoints.tfsteamprojectendpoint.yaml
- docs/data/classes/reference.endpoints.tfsteamsettingsendpoint.yaml
- docs/data/classes/reference.endpoints.tfsworkitemendpoint.yaml
- docs/data/classes/reference.processors.keepoutboundlinktargetprocessor.yaml
- docs/data/classes/reference.tools.tfsvalidaterequiredfieldtool.yaml
- docs/data/classes/reference.tools.tfsworkitemtypevalidatortool.yaml
- docs/static/schema/configuration.schema.json
- docs/static/schema/schema.tools.tfsvalidaterequiredfieldtool.json
- docs/static/schema/schema.tools.tfsworkitemtypevalidatortool.json
- src/MigrationTools.Clients.TfsObjectModel/Tools/TfsValidateRequiredFieldTool.cs
- src/MigrationTools.Clients.TfsObjectModel/Tools/TfsValidateRequiredFieldToolOptions.cs
- Implemented a check in TfsValidateRequiredFieldTool.cs to skip validation for excluded work item types, with debug logging.
- Added an `Exclusions` property in TfsValidateRequiredFieldToolOptions.cs to allow users to specify work item types to exclude from validation, including documentation on its usage.
- Removed deprecated commented-out code related to configuration validation in TfsValidateRequiredFieldTool.cs.
Resolves: #2897
Co-authored-by: rpollick <rpollick@users.noreply.github.com>
> Add exclusions for work item types in validation

- src/MigrationTools.Clients.TfsObjectModel/Processors/TfsWorkItemTypeValidatorProcessor.cs
- src/MigrationTools.Clients.TfsObjectModel/Processors/TfsWorkItemTypeValidatorProcessorOptions.cs
This PR follows my previous PR #2894 that implements work item type validator tool. I also implemented the porcessor, which uses tool and just validates work item types.
This validation is run automatically during work item migrations, but I need (and hope it is useful for others) just to validate things ad do not continue even if everything is OK. I was whinking implementing it as separate processor, or just some boolean option in `TfsWorkItemMigrationProcessor` and chose separate processor. I think it is cleaner because it is simple and it is very clear what is this processor for.
The processor supports just one option `StopIfValidationFails`. If `true`, the migration process will stop if the validation fails – this is the default. If set to `false`, the migration process (other …
> Implement work item type validator processor

- docs/data/classes/reference.tools.tfsusermappingtool.yaml
- docs/static/schema/configuration.schema.json
- docs/static/schema/schema.tools.tfsusermappingtool.json
- src/MigrationTools.Clients.TfsObjectModel/Tools/TfsUserMappingTool.cs
- src/MigrationTools.Clients.TfsObjectModel/Tools/TfsUserMappingToolOptions.cs
Replaced hardcoded "Project Collection Valid Users" string in `TfsUserMappingTool.cs` with a configurable property `Options.ProjectCollectionValidUsersGroupName`. Added this property to `TfsUserMappingToolOptions.cs` to allow customization of the group name, with a default value of "Project Collection Valid Users".
Fixes:  #2895
Co-authored-by: sl-io <sl-io@users.noreply.github.com>
> Refactor user group name handling in TfsUserMappingTool

- docs/layouts/_shortcodes/class-options.html
- replace table layout with responsive div-based layout
- use Bootstrap classes for consistent styling across devices
- enhance readability on smaller screens with contextual labels
> 💄 style(html): improve table responsiveness in class-options

- .github/instructions/docs.content.docs.list.instructions.md
- .github/instructions/docs.content.docs.single.instructions.md
- docs/content/docs/reference/tools/stringmanipulatortool/index.md
- docs/content/docs/reference/tools/tfsattachmenttool/index.md
- docs/content/docs/reference/tools/tfschangesetmappingtool/index.md
- docs/content/docs/reference/tools/tfsembededimagestool/index.md
- docs/content/docs/reference/tools/tfsgitrepositorytool/index.md
- docs/content/docs/reference/tools/tfsnodestructuretool/index.md
- docs/content/docs/reference/tools/tfsrevisionmanagertool/index.md
- docs/content/docs/reference/tools/tfsteamsettingstool/index.md
- docs/content/docs/reference/tools/tfsusermappingtool/index.md
- docs/content/docs/reference/tools/tfsvalidaterequiredfieldtool/index.md
- docs/content/docs/reference/tools/tfsworkitemembededlinktool/index.md
- docs/content/docs/reference/tools/tfsworkitemlinktool/index.md
- docs/content/docs/reference/tools/tfsworkitemtypevalidatortool/index.md
- docs/content/docs/reference/tools/workitemtypemappingtool/index.md
This pull request introduces comprehensive improvements to both the documentation standards and the technical documentation for several migration tools. It adds new standards for list and single documentation pages, ensuring consistency and SEO-friendliness, and significantly enhances the technical reference docs for the String Manipulator Tool, TFS Attachment Tool, and TFS Changeset Mapping Tool with clearer structure, expanded configuration examples, troubleshooting, and best practices.
**Documentation Standards and Structure**
* Added new instruction file `.github/instructions/docs.content.docs.list.instructions.md` to define standards for list pages, including front matter, content guidelines, and rules for maintaining consistency and SEO alignment.
* Refined and renamed …
> Refactor documentation for tools

- src/MigrationTools.Clients.TfsObjectModel/Tools/TfsWorkItemTypeValidatorTool.cs
When trying to migrate from Azure Devops 2019 to Azure Devops 2022, in user story , Resolved reason which is of type Microsoft.VSTS.Common.ResolvedReason , has extra value "Will not fix" in target values.
in source code, instead of checking equality of source field count and target field count modified check to targetfields.count< sourcefields.count.
Source Azure Devops Version : 2019
Target Azure Devops Version: 2022
Microsoft.VSTS.Common.ResolvedReason in 2022 , has extra value "will not fix". There is no way in Azure Devops 2022 or Azure Devops 2019 to modify Microsoft.VSTS.Common.ResolvedReason. Therefore, instead of checking number of fields, checking all allowed source field values in allowed target field values is enough. 
Also modified name of method from **AllowedValuesAreSame** …
> #2952 issue ,check target field allowed values contain all allowed source  field values

- docs/data/classes/reference.endpoints.tfsendpoint.yaml
- docs/data/classes/reference.endpoints.tfsteamprojectendpoint.yaml
- docs/data/classes/reference.endpoints.tfsteamsettingsendpoint.yaml
- docs/data/classes/reference.endpoints.tfsworkitemendpoint.yaml
- docs/data/classes/reference.processors.tfsworkitemmigrationprocessor.yaml
- docs/static/schema/configuration.schema.json
- docs/static/schema/schema.endpoints.tfsendpoint.json
- docs/static/schema/schema.endpoints.tfsteamprojectendpoint.json
- docs/static/schema/schema.endpoints.tfsteamsettingsendpoint.json
- docs/static/schema/schema.endpoints.tfsworkitemendpoint.json
- docs/static/schema/schema.processors.tfsworkitemmigrationprocessor.json
- src/MigrationTools.Clients.TfsObjectModel/Endpoints/TfsEndpointOptions.cs
- src/MigrationTools.Clients.TfsObjectModel/Processors/TfsWorkItemMigrationProcessor.cs
- src/MigrationTools.Clients.TfsObjectModel/Processors/TfsWorkItemMigrationProcessorOptions.cs
Users are reporting confusion when rerunning the migration tool. Specifically, they expect changes to sync across but find that nothing happens when `UpdateCreatedDate` and `UpdateCreatedBy` are set to `false`.
This confusion arises because:
* When `UpdateCreatedDate` and `UpdateCreatedBy` are `false`, revisions in the source must have a higher date than the target, otherwise they are filtered out.
* This behaviour is correct but not obvious, leading users to believe updates are being skipped incorrectly.
* These flags were originally introduced only to support TFS 2008, which does not allow setting revision dates in the past.
* If `UpdateCreatedDate` and `UpdateCreatedBy` are set to `false`, rerunning the tool does not sync new changes unless the revision date in the source is newer than …
> Confusing behaviour of `UpdateCreatedDate` and `UpdateCreatedBy` in `TfsWorkItemMigrationProcessor`

- src/MigrationTools.Clients.TfsObjectModel/Processors/TfsWorkItemMigrationProcessor.cs
- src/MigrationTools.Clients.TfsObjectModel/Processors/TfsWorkItemTypeValidatorProcessor.cs
- src/MigrationTools.Clients.TfsObjectModel/Tools/TfsWorkItemTypeValidatorTool.cs
This PR solves the first item in [improve work item type validation list](https://github.com/nkdAgility/azure-devops-migration-tools/discussions/2951).
Reflected work item ID is mandatory for proper work item migration. So validation of this field is performed always, even if the validator tool itself is disabled. This field was validated always before my addition to validate full work item types, so I just returned back the old behavior.
> Validation of reflected work item ID is mandatory

- appsettings.json
- docs/data/classes/reference.tools.tfsworkitemtypevalidatortool.yaml
- docs/static/schema/configuration.schema.json
- docs/static/schema/schema.tools.tfsworkitemtypevalidatortool.json
- src/MigrationTools.Clients.TfsObjectModel/ServiceCollectionExtensions.cs
- src/MigrationTools.Clients.TfsObjectModel/Tools/TfsWorkItemTypeValidatorTool.cs
- src/MigrationTools.Clients.TfsObjectModel/Tools/TfsWorkItemTypeValidatorToolOptions.cs
- src/MigrationTools.Clients.TfsObjectModel/Tools/TfsWorkItemTypeValidatorToolOptionsValidator.cs
Fixes https://github.com/nkdAgility/azure-devops-migration-tools/pull/2971#issuecomment-3245849088
> TfsWorkItemTypeValidatorTool: fix default excluded WITs handling

- .powershell/docs/Get-DiscussionId.ps1
- docs/content/docs/get-started/validation/index.md
This pull request primarily enhances how documentation URLs are generated in the `Get-DiscussionId.ps1` script by including the class type name in the URL path. It introduces a new function to extract the class type name from data files and updates all relevant code paths to use this value. Additionally, a minor metadata update is made to a documentation markdown file.
**Improvements to documentation URL generation:**
* Added a new function `Get-ClassTypeNameFromDataFile` to extract the `typeName` property from YAML data files, with error handling for missing or invalid files. (.powershell/docs/Get-DiscussionId.ps1)
* Updated all references to data file paths to use the correct directory: `.\docs\data\classesThis pull request primarily enhances how documentation URLs are generated in the …
> Add Get-ClassTypeNameFromDataFile function and update documentation links

- src/MigrationTools.Clients.TfsObjectModel/Tools/TfsWorkItemLinkTool.cs
Refactored `CreateHyperlink` to improve clarity and maintainability.
- Changed `sourceLinkAbsoluteUri` declaration to `string`.
- Added `IsValidHyperlink` method to validate hyperlink format and protocol.
- Introduced `GetAbsoluteUri` method for reusable URI parsing logic.
- Enhanced logging to provide detailed warnings for invalid hyperlinks.
- Improved code readability by modularizing validation and URI handling.
> Add hyperlink validation and refactor `CreateHyperlink`
