nkdAgility/azure-devops-migration-tools

GitVersion.yml
src/VstsSyncMigrator.Core/Execution/MigrationContext/WorkItemMigrationContext.cs

@MrHinsh Had some 'issues' getting my branches up to date so just re-created in the end. Have updated the version number to 7.1.0 as requested in the original PR.

Issue11: The value for the field 'Closed Date' cannot be changed

---

src/VstsSyncMigrator.Core/Execution/MigrationContext/TestConfigurationsMigrationContext.cs

Fix is to loop over the source configuration variables when migrating so they can be added to the target configuration. Previously it was looping over the target variables which would always be an empty collection and so nothing would be added.

Bug in adding variables to test configuration

---

GitVersion.yml
docs/configuration.md
docs/index.md
docs/usage/command-line.md
src/VstsSyncMigrator.Core/Configuration/EngineConfiguration.cs
src/VstsSyncMigrator.Core/Configuration/Processing/FixGitCommitLinksConfig.cs
src/VstsSyncMigrator.Core/Execution/ProcessingContext/FixGitCommitLinks.cs

Feature allow specify target git repo name for fixing git commit links

---

src/VstsSyncMigrator.Console/Program.cs
src/VstsSyncMigrator.Core/Configuration/Processing/TestPlansAndSuitsMigrationConfig.cs
src/VstsSyncMigrator.Core/Configuration/Processing/WorkItemMigrationConfig.cs
src/VstsSyncMigrator.Core/Execution/ComponentContext/TeamProjectContext.cs
src/VstsSyncMigrator.Core/Execution/ComponentContext/TfsQueryContext.cs
src/VstsSyncMigrator.Core/Execution/ComponentContext/WorkItemStoreContext.cs
src/VstsSyncMigrator.Core/Execution/FieldMaps/FieldMapBase.cs
src/VstsSyncMigrator.Core/Execution/FieldMaps/FieldToTagFieldMap.cs
src/VstsSyncMigrator.Core/Execution/FieldMaps/FieldValuetoTagMap.cs
src/VstsSyncMigrator.Core/Execution/FieldMaps/IFieldMap.cs
src/VstsSyncMigrator.Core/Execution/FieldMaps/RegexFieldMap.cs
src/VstsSyncMigrator.Core/Execution/FieldMaps/TreeToTagFieldMap.cs
src/VstsSyncMigrator.Core/Execution/MigrationContext/AttachementImportMigrationContext.cs
src/VstsSyncMigrator.Core/Execution/MigrationContext/MigrationContextBase.cs
src/VstsSyncMigrator.Core/Execution/MigrationContext/TestPlansAndSuitsMigrationContext.cs
src/VstsSyncMigrator.Core/Execution/MigrationContext/WorkItemMigrationContext.cs
src/VstsSyncMigrator.Core/Execution/ProcessingContext/ProcessingContextBase.cs
src/VstsSyncMigrator.Core/MigrationEngine.cs

* FieldMap need information of stores to migrate Shared Steps in Test Cases.
* To migrate a Shared Step, the Shared Step need to be migrated first -> ORDER BY of selected WI are now sorted by (WI name, ChangeDate desc).
* When developing in DEBUG mode it does not make sence to warn of newer version.
* Stacktrace is written when exceptions occur

Migration of Shared Steps

---

src/VstsSyncMigrator.Console/Program.cs
src/VstsSyncMigrator.Core/Configuration/Processing/TestPlansAndSuitsMigrationConfig.cs
src/VstsSyncMigrator.Core/Configuration/Processing/WorkItemMigrationConfig.cs
src/VstsSyncMigrator.Core/Execution/ComponentContext/TeamProjectContext.cs
src/VstsSyncMigrator.Core/Execution/ComponentContext/TfsQueryContext.cs
src/VstsSyncMigrator.Core/Execution/ComponentContext/WorkItemStoreContext.cs
src/VstsSyncMigrator.Core/Execution/FieldMaps/FieldMapBase.cs
src/VstsSyncMigrator.Core/Execution/FieldMaps/FieldToTagFieldMap.cs
src/VstsSyncMigrator.Core/Execution/FieldMaps/FieldValuetoTagMap.cs
src/VstsSyncMigrator.Core/Execution/FieldMaps/IFieldMap.cs
src/VstsSyncMigrator.Core/Execution/FieldMaps/RegexFieldMap.cs
src/VstsSyncMigrator.Core/Execution/FieldMaps/TreeToTagFieldMap.cs
src/VstsSyncMigrator.Core/Execution/MigrationContext/AttachementImportMigrationContext.cs
src/VstsSyncMigrator.Core/Execution/MigrationContext/TestPlansAndSuitsMigrationContext.cs
src/VstsSyncMigrator.Core/Execution/MigrationContext/WorkItemMigrationContext.cs
src/VstsSyncMigrator.Core/Execution/ProcessingContext/ProcessingContextBase.cs
src/VstsSyncMigrator.Core/MigrationEngine.cs

Reverts nkdAgility/vsts-sync-migration#23

Revert "Migration of Shared Steps"

---

src/VstsSyncMigrator.Core/Execution/MigrationContext/AttachementExportMigrationContext.cs

Updated the download function for attachments to use the WorkItemServer class instead of the WebClient. WebClient was not authenticating the user correctly.
Fixes #24

Updated Attachement downloading function to use the WorkItemServer.

---

src/VstsSyncMigrator.Core/Execution/MigrationContext/AttachementImportMigrationContext.cs

Checks if attachment was already uploaded and skip, Add counter for skipped attachments.

Improving attachment import 

---

src/VstsSyncMigrator.Core/Execution/MigrationContext/NodeStructuresMigrationContext.cs
src/VstsSyncMigrator.Core/Execution/MigrationContext/WorkItemMigrationContext.cs

Lets NodeStructuresMigration Processor to migrate dates of iterations

Migrate date of iterations

---

src/VstsSyncMigrator.Core/Execution/MigrationContext/WorkItemMigrationContext.cs
src/VstsSyncMigrator.Core/Execution/MigrationContext/WorkItemRevisionReplayMigrationContext.cs

This is a change to VSTS Sync Migration Tool Signature which is available in all workitems migrated using this tool. The signature has been changed from
Migrated by naked Agility Limited's open source VSTS/TFS Migrator
to
Migrated by VSTS/TFS Sync Migration Tool open source.

VSTS Sync Migrator Signature Update

---

src/VstsSyncMigrator.Core/Execution/MigrationContext/AttachementImportMigrationContext.cs

Improve deletion of attachments

AttachementImportMigrationContext: Improve deletion of attachments

---

src/VstsSyncMigrator.Core/Configuration/Processing/HtmlFieldEmbeddedImageMigrationConfig.cs
src/VstsSyncMigrator.Core/Execution/MigrationContext/HtmlFieldEmbeddedImageMigrationContext.cs

HtmlFieldEmbeddedImageMigrationContext: 
Fix AlternateCredentials Null Reference Exception
Improving logging
Add QueryBit parameter
FixHtmlAttachmentLinks(): Add support for opposite schema (http-https) in url

Improvements for 7.5.20

---

src/VstsSyncMigrator.Core/Configuration/Processing/HtmlFieldEmbeddedImageMigrationConfig.cs
src/VstsSyncMigrator.Core/Execution/MigrationContext/AttachementImportMigrationContext.cs
src/VstsSyncMigrator.Core/Execution/MigrationContext/HtmlFieldEmbeddedImageMigrationContext.cs

**HtmlFieldEmbeddedImageMigrationContext:** 
- Add possible candidates counter
- Improve logging
- Fixes in getting opposite schema url
- Add config parameter 'FromAnyCollection' for migrate images across whole TFS server
- Improvment in matching (exclude case sensitive mismatches)
**AttachementImportMigrationContext:** 
- Improve logging

Html field embedded image migration impovments

---

src/VstsSyncMigrator.Core/Execution/MigrationContext/WorkItemMigrationContext.cs

This fix the issue #154. 
I removed the "[System.Tags]" from the query.

Fix issue #154

---

src/VstsSyncMigrator.Console/Program.cs
src/VstsSyncMigrator.Core/Execution/FieldMaps/FieldBlankMap.cs
src/VstsSyncMigrator.Core/Execution/FieldMaps/FieldMapBase.cs
src/VstsSyncMigrator.Core/Execution/FieldMaps/FieldMergeMap.cs
src/VstsSyncMigrator.Core/Execution/FieldMaps/FieldToFieldMap.cs
src/VstsSyncMigrator.Core/Execution/FieldMaps/FieldToTagFieldMap.cs
src/VstsSyncMigrator.Core/Execution/FieldMaps/FieldValueMap.cs
src/VstsSyncMigrator.Core/Execution/FieldMaps/FieldValuetoTagMap.cs
src/VstsSyncMigrator.Core/Execution/FieldMaps/IFieldMap.cs
src/VstsSyncMigrator.Core/Execution/FieldMaps/MultiValueConditionalMap.cs
src/VstsSyncMigrator.Core/Execution/FieldMaps/RegexFieldMap.cs
src/VstsSyncMigrator.Core/Execution/FieldMaps/TreeToTagFieldMap.cs
src/VstsSyncMigrator.Core/Execution/MigrationContext/WorkItemMigrationContext.cs
src/VstsSyncMigrator.Core/Execution/MigrationContext/WorkItemRevisionReplayMigrationContext.cs
src/VstsSyncMigrator.Core/MigrationEngine.cs

I've added some more error detail to the field mapping outputs which helped me diagnose an issue that I had. Maybe it's helpful for others, too.

Add some more error details

---

src/VstsSyncMigrator.Core/Execution/MigrationContext/HtmlFieldEmbeddedImageMigrationContext.cs

It actually happened to me that everything appeared to be working, but the downloaded file (something.png) was actually containing HTML text with the VSTS/Azure DevOps Login page HTML :)
So this PR verifies the downloaded image is really a picture for additional safety

Add a check that the downloaded image is really an image

---

src/VstsSyncMigrator.Core/Configuration/Processing/TestPlansAndSuitesMigrationConfig.cs
src/VstsSyncMigrator.Core/Execution/MigrationContext/TestPlansAndSuitesMigrationContext.cs

- Fix "The URL specified has a potentially unsafe URL protocol. " by removing invalid links when configured
- enhance resolving of target identity (it failed for me when we changed some e-mail addresses around because of some caching, so it tries a refresh of data now)
Should fix #178

 Small refactorings, fix "potentially unsafe URL protocol. ", enhance resolving of target identity

---

docs/configuration.md
docs/index.md
docs/usage/command-line.md
src/VstsSyncMigrator.Core/Configuration/EngineConfiguration.cs
src/VstsSyncMigrator.Core/Configuration/FieldMap/FieldtoFieldMultiMapConfig.cs
src/VstsSyncMigrator.Core/Execution/FieldMaps/FieldMapBase.cs
src/VstsSyncMigrator.Core/Execution/FieldMaps/FieldMergeMap.cs
src/VstsSyncMigrator.Core/Execution/FieldMaps/FieldValueMap.cs
src/VstsSyncMigrator.Core/Execution/FieldMaps/FieldtoFieldMultiMap.cs
src/VstsSyncMigrator.Core/VstsSyncMigrator.Core.csproj

- Added FieldtoFieldMultiMap for mapping multiple fields en-masse.
- Added null checks and type safety to FieldValueMap and FieldMergeMap.
- Added log for exceptions in FieldMapBase to they aren't transparent in the logs.

FieldToFieldMultiMap, Type Safety and Null Checks.

---

src/VstsSyncMigrator.Core/Execution/MigrationContext/WorkItemMigrationContext.cs

Fix for issue reported in #310

Fix bug in FilterWorkItemsThatAlreadyExistInTarget

---

src/VstsSyncMigrator.Core/Execution/MigrationContext/WorkItemMigrationContext.cs

#326 
Added System.RemoteLinkCount to the PopulateIgnoreList function to ensure that the field is ignored when populating the new work item fields.

Added System.RemoteLinkCount to the PopulateIgnoreList function.

---

src/VstsSyncMigrator.Core/Execution/MigrationContext/WorkItemMigrationContext.cs

There was still some method duplication from the merge. Now the tool has a single code run and removes revisions that are not relevant for the tip.

Removed duplication between Replay and Tip

---

src/VstsSyncMigrator.Core/Execution/ComponentContext/WorkItemStoreContext.cs

Fix bug when a work item ID has been deleted and results in an error  untill its cleaned off the server.

Fix exception when Work Item ID has been Deleted from Targert

---

src/VstsSyncMigrator.Console/Program.cs
src/VstsSyncMigrator.Core/Configuration/EngineConfiguration.cs
src/VstsSyncMigrator.Core/Configuration/Processing/FixGitCommitLinksConfig.cs
src/VstsSyncMigrator.Core/Execution/MigrationContext/WorkItemMigrationContext.cs
src/VstsSyncMigrator.Core/Execution/OMatics/RepoOMatic.cs
src/VstsSyncMigrator.Core/Execution/OMatics/WorkItemLinkOMatic.cs
src/VstsSyncMigrator.Core/Execution/ProcessingContext/FixGitCommitLinks.cs
src/VstsSyncMigrator.Core/MigrationEngine.cs
src/VstsSyncMigrator.Core/VstsSyncMigrator.Core.csproj

This adds Git Commit Fix to the core Work Item migration. +semver: minor
note: Pull Requests do not migrate.

Fold git commit fix

---

src/VstsSyncMigrator.Core/Execution/OMatics/RepoOMatic.cs

Since Pull Requests dont get migrated we need to remove Pull Request links

Remove Pull Requests

---

src/VstsSyncMigrator.Core/Execution/MigrationContext/WorkItemMigrationContext.cs
src/VstsSyncMigrator.Core/Execution/OMatics/AttachmentOMatic.cs
src/VstsSyncMigrator.Core/Execution/OMatics/RepoOMatic.cs
src/VstsSyncMigrator.Core/Execution/OMatics/WorkItemLinkOMatic.cs

Changed the system so that it does not save after every link or attachement. All links and attachments are added and then save is called!

Save Less!

---

src/VstsSyncMigrator.Core/Execution/MigrationContext/TestPlansAndSuitesMigrationContext.cs

Some simple renovations to make output more readable and to understand what is left to do.

Test Plan Renovation #1

---

src/VstsSyncMigrator.Core/Configuration/EngineConfiguration.cs
src/VstsSyncMigrator.Core/Configuration/Processing/TeamMigrationConfig.cs
src/VstsSyncMigrator.Core/Configuration/Processing/TestPlansAndSuitesMigrationConfig.cs
src/VstsSyncMigrator.Core/Configuration/Processing/WorkItemMigrationConfig.cs
src/VstsSyncMigrator.Core/Configuration/Processing/WorkItemPostProcessingConfig.cs
src/VstsSyncMigrator.Core/Configuration/Processing/WorkItemUpdateConfig.cs

Now the default-values don't only apply for newly created configs vai init-command but also for unconfigured properties/parameters

*moved default-values from engine to models

---

src/VstsSyncMigrator.Core/Execution/MigrationContext/TestPlansAndSuitesMigrationContext.cs

Fix NullReference exception and adding extra validation details when updating work items

Fix NullReference exception and adding extra validation details

---

src/VstsSyncMigrator.Core/Execution/MigrationContext/WorkItemMigrationContext.cs

Updated to support rerunning older migrations with zero revissions.

---

src/VstsSyncMigrator.Core/Configuration/EngineConfiguration.cs

In the default configuration.json that is generated, I'd like to add a mapping for the work item state "Removed". Maybe this will be useful for others than myself.
Also: thank you for creating this great tool and making it open source! ❤

Added mapping for work item state "Removed"

---

src/VstsSyncMigrator.Core/Execution/ComponentContext/TfsQueryContext.cs

fixes #477 
Now you can also use @TeamProject in the querybit and it will be replaced by the source or target project.

fix(query context): only replace value for keys with quotes when not part of larger string

---

src/VstsSyncMigrator.Core/Execution/OMatics/WorkItemLinkOMatic.cs

Do not migrate build links

---

README.md
src/VstsSyncMigrator.Extension/README.md
src/VstsSyncMigrator.Extension/vss-extension.json

Updated links to Q&A to https://stackoverflow.com/questions/tagged/azure-devops-migration-tools

Docu patch1

---

src/VstsSyncMigrator.Core/Execution/MigrationContext/TestPlansAndSuitesMigrationContext.cs

If multiple identities are returned the code fails.  Catch the exception and try looking up the identity using the Account Name.  Addresses Issue #508

Catch MultipleIdentitiesFound exception

---

.editorconfig
VstsSyncMigrator.sln
src/VstsSyncMigrator.Console/Program.cs
src/VstsSyncMigrator.Core/Execution/MigrationContext/NodeStructuresMigrationContext.cs

Change in the algorithm:
- When iterating through the "Iterations", I refactored to have always run the setIterationDates, regardless if the node has been newly created or already existed.
In my scenario, the Target Team Project already had been populated with Sprints 1..6, but no dates, however the source Team Project had dates.
Small changes:
- Added a .editorConfig because my IDE settings were different and messed the tabs.
- In program.cs, at the end of the process, added a message to the user to hit a key when in debug.

Added .editorConfig and changed iteration node creation

---

src/VstsSyncMigrator.Core/Execution/MigrationContext/WorkItemMigrationContext.cs

Added hard coded skip of Test Plan and Test Suite work items for #511

Added hard coded skip of Test Plan and Test Suite work items for #511

---

src/VstsSyncMigrator.Console.Tests/app.config
src/VstsSyncMigrator.Console/App.config
src/VstsSyncMigrator.Console/Program.cs
src/VstsSyncMigrator.Console/VstsSyncMigrator.Console.csproj
src/VstsSyncMigrator.Console/packages.config
src/VstsSyncMigrator.Core/Execution/ComponentContext/TfsQueryContext.cs
src/VstsSyncMigrator.Core/Execution/MigrationContext/WorkItemMigrationContext.cs
src/VstsSyncMigrator.Core/Execution/OMatics/AttachmentOMatic.cs
src/VstsSyncMigrator.Core/MigrationEngine.cs
src/VstsSyncMigrator.Core/VstsSyncMigrator.Core.csproj
src/VstsSyncMigrator.Core/app.config
src/VstsSyncMigrator.Core/packages.config

I have updated much of the core functionality to the new Serilog logger which give a much nicer view.

Migrate to serilog

---

src/MigrationTools/Core/Engine/Containers/ChangeSetMappingContainer.cs
src/MigrationTools/Core/Engine/Containers/EngineContainer.cs
src/MigrationTools/Core/Engine/Containers/FieldMapContainer.cs
src/MigrationTools/Core/Engine/Containers/GitRepoMapContainer.cs
src/MigrationTools/Core/Engine/Containers/ProcessorContainer.cs
src/MigrationTools/Core/Engine/Containers/TypeDefinitionMapContainer.cs
src/VstsSyncMigrator.Console/Program.cs
src/VstsSyncMigrator.Core.Tests/MigrationEngineTests.cs
src/VstsSyncMigrator.Core/Execution/MigrationContext/TestConfigurationsMigrationContext.cs
src/VstsSyncMigrator.Core/Execution/MigrationContext/TestVeriablesMigrationContext.cs
src/VstsSyncMigrator.Core/MigrationEngine.cs

Updated IHost to IServiceProvider and added missing Processors

Abstraction#3

---

docs/getting-started.md

Small doc update for the path to the tool 😊

path to tool is different to the docs

---

docs/index.md

Also updated other small changes while editing the index page

fix table in index docs

---

GitVersion.yml
docs/configuration.md
docs/getting-started.md
docs/index.md
src/MigrationTools.Clients.AzureDevops.ObjectModel/Clients/MigrationClient.cs
src/MigrationTools.Clients.AzureDevops.ObjectModel/Clients/WorkItemMigrationClient.cs
src/MigrationTools.Clients.AzureDevops.ObjectModel/Extensions.cs
src/MigrationTools.Host/StartupService.cs
src/MigrationTools/Clients/IWorkItemMigrationClient.cs
src/MigrationTools/Clients/WorkItemMigrationClientBase.cs
src/MigrationTools/Configuration/Processing/TestPlansAndSuitesMigrationConfig.cs
src/MigrationTools/CustomDiagnostics/CustomConverter.cs
src/MigrationTools/Engine/Containers/ChangeSetMappingContainer.cs
src/MigrationTools/Engine/Containers/EngineContainer.cs
src/MigrationTools/Engine/Containers/FieldMapContainer.cs
src/MigrationTools/Engine/Containers/GitRepoMapContainer.cs
src/MigrationTools/Engine/Containers/ProcessorContainer.cs
src/MigrationTools/Engine/Containers/TypeDefinitionMapContainer.cs
src/VstsSyncMigrator.Core/Execution/ComponentContext/TestManagementContext.cs
src/VstsSyncMigrator.Core/Execution/MigrationContext/TestPlansAndSuitesMigrationContext.cs
src/VstsSyncMigrator.Core/Execution/MigrationContext/WorkItemMigrationContext.cs

A little time resolving some https://sonarcloud.io/dashboard?id=vsts-sync-migrator%3Amaster
- All Security Issues resolved
- All blocking issues & critical issues resolved
- assortment of other issues resolved.

Sonar Cube Bug Bash

---

src/MigrationTools.Host/MigrationToolHost.cs
src/MigrationTools.Host/MigrationTools.Host.csproj
src/MigrationTools/Configuration/EngineConfiguration.cs
src/MigrationTools/Configuration/EngineConfigurationBuilder.cs
src/MigrationTools/CustomDiagnostics/CustomConverter.cs
src/VstsSyncMigrator.Core/Execution/ProcessingContext/ExportProfilePictureFromADContext.cs
src/VstsSyncMigrator.Core/Execution/ProcessingContext/ImportProfilePictureContext.cs

Problem with version number on MigrationTools.Host since it was overriding the value from the build.props file

removed duplicates of properties already existing in build.props

---

src/MigrationTools/Engine/Containers/GitRepoMapContainer.cs

This should resolve at least the null reference in #625

Ypdate GitRepoMapContainer to never be null

---

src/MigrationTools/Configuration/Processing/WorkItemMigrationConfig.cs
src/VstsSyncMigrator.Core/Execution/MigrationContext/WorkItemMigrationContext.cs

Added choice wheater the Migration comment in the Discussion section should be created or not

Choice of genreating Migration comment

---

src/MigrationTools.Clients.AzureDevops.ObjectModel/Enrichers/EmbededImagesRepairEnricher.cs

Changed the spelling mistake "attachemtnts" to "attachments"

Fix EmbededImagesRepairEnricher spelling mistake

---

docs/Processors/WorkItemMigrationConfig.md
src/MigrationTools.Clients.AzureDevops.ObjectModel/FieldMaps/MultiValueConditionalMap.cs

_MS.ProcessedByMetricExtractors: (Name:'Exceptions', Ver:'1.1')
Account Id: <undefined>
Application version: 11.6.4.0
Auth user Id: <undefined>
Browser version: <not collected>
City: Mechanicsville
Client IP address: 0.0.0.0
Cloud role instance: XXXXXXXXXXX
Cloud role name: <undefined>
Country or region: United States
currentWorkItem: 1
Device model: <undefined>
Device type: PC
Event time: 16/10/2020, 10:30:51
Exception type: System.NullReferenceException
Failed method: MigrationTools.Clients.AzureDevops.ObjectModel.FieldMaps.MultiValueConditionalMap.fieldsExist
MachineName: XXXXXXXX
MessageTemplate: Field mapp fault
Operating system: Microsoft Windows NT 6.2.9200.0
Operation Id: <undefined>
Operation name: <undefined>
Parent Id: <undefined>
Problem Id: System.NullReferenceException at …

Added protection for missing FieldsAndValues on Source or Target

---

CONTRIBUTING.md
README.md
docs/getting-started.md
docs/server-configuration.md

Great tool. Thanks for developing it.  Here are a few grammar and typo fixes. Sorry also for multiple commits, I fixed the typos using my iPad.
Also the getting started page has a typo that I can’t reach. It is at https://nkdagility.github.io/azure-devops-migration-tools/getting-started and says “experiances” rather than “experienced”.
I apologize if any of these fixes are due to british english vs american english cultural writing styles. I do not believe that they are.
Keep up the good work on the project. -Michael

I fixed a few typos. I didn’t see an issue for these but just noticed them while reading.

---

docs/Processors/WorkItemMigrationConfig.md

fixes #686
I took the draft content I created in the issue and tidied it up.
Please correct me if you think for the content is wrong or missing valid examples

Added documentation on nodepaths

---

src/MigrationTools.Clients.FileSystem.Tests/Endpoints/FileSystemWorkItemEndpointTests.cs
src/MigrationTools.Clients.FileSystem.Tests/ServiceProviderHelper.cs
src/MigrationTools.Clients.InMemory.Tests/Endpoints/InMemoryWorkItemEndpointTests.cs
src/MigrationTools.Clients.InMemory.Tests/ServiceProviderHelper.cs
src/MigrationTools.Integration.Tests/ServiceProviderHelper.cs
src/MigrationTools.Tests/ServiceProviderHelper.cs
src/MigrationTools/MigrationTools.csproj
src/MigrationTools/ServiceCollectionExtensions.cs

Updated to remove AI telemetry from unit tests, and add the logger to all unit tests

AI & Logging for UnitTests

---

src/MigrationTools.Clients.AzureDevops.ObjectModel/ProcessorEnrichers/TfsValidateRequiredField.cs
src/MigrationTools.Clients.AzureDevops.ObjectModel/ProcessorEnrichers/TfsValidateRequiredFieldOptions.cs
src/MigrationTools.Clients.AzureDevops.ObjectModel/ServiceCollectionExtensions.cs
src/MigrationTools/ProcessorEnrichers/WorkItemProcessorEnrichers/FilterWorkItemsThatAlreadyExistInTarget.cs
src/MigrationTools/ProcessorEnrichers/WorkItemProcessorEnrichers/WorkItemProcessorEnricher.cs
src/VstsSyncMigrator.Core/Execution/MigrationContext/WorkItemMigrationContext.cs

This should close #695 and any issues that relate to the ReflectedWorkItemId field not being present on work items.

Added validation for each work item type that is in scope for a query

---

src/VstsSyncMigrator.Core/Execution/MigrationContext/TeamMigrationContext.cs

Added debug that might help #692

---

src/MigrationTools.Clients.AzureDevops.ObjectModel/TfsExtensions.cs
src/VstsSyncMigrator.Core/Execution/MigrationContext/WorkItemMigrationContext.cs

Extra logging to help with #717

Extra logging to help with #717

---

configuration.json
configuration2.json
src/MigrationTools.Clients.AzureDevops.ObjectModel.Tests/Endpoints/TfsWorkItemEndPointTests.cs
src/MigrationTools.Clients.AzureDevops.ObjectModel/Endpoints/TfsWorkItemEndPoint.cs
src/MigrationTools.Clients.AzureDevops.ObjectModel/Endpoints/TfsWorkItemEndPointOptions.cs
src/MigrationTools.Clients.AzureDevops.ObjectModel/_EngineV1/Configuration/TfsTeamProjectConfig.cs
src/MigrationTools.Clients.AzureDevops.ObjectModel/_Enginev1/Clients/TfsMigrationClient.cs
src/MigrationTools.Integration.Tests/AzureDevOpsObjectModelTests.cs
src/MigrationTools/Tests/TestingConstants.cs
src/VstsSyncMigrator.Core/Execution/ProcessingContext/WorkItemDelete.cs

Added beeter prompt for auth for #712 but requires new config option +semver: minor

Fix for Incorrect Auth

---

src/MigrationTools.Clients.AzureDevops.ObjectModel/Enrichers/TfsGitRepositoryEnricher.cs
src/MigrationTools.Clients.AzureDevops.ObjectModel/Enrichers/TfsWorkItemLinkEnricher.cs
src/MigrationTools.Clients.AzureDevops.ObjectModel/TfsExtensions.cs

Fixes issue that the Author of every Comment is "Migration" instead of the actual Author
closes #685

Wrong comment author shown

---

configuration.json
src/MigrationTools.Clients.AzureDevops.ObjectModel/ProcessorEnrichers/TfsValidateRequiredField.cs

Fix for #722 so that it checks the target store for the fields rather than the source.

Fix for #722 

---

src/MigrationTools.Clients.AzureDevops.ObjectModel/TfsExtensions.cs

Extra Debug for Save

---

src/MigrationTools.Host.Tests/MigrationHostTests.cs
src/MigrationTools.Host.Tests/MigrationTools.Host.Tests.csproj
src/MigrationTools/ExecuteHostedService.cs
src/MigrationTools/ServiceCollectionExtensions.cs
src/MigrationTools/_EngineV1/Configuration/EngineConfiguration.cs
src/MigrationTools/_EngineV1/Containers/ChangeSetMappingContainer.cs

Work in progress to smooth out startup and configuration loading kinks. Just need to get it in piece by piece, since @MrHinsh is so active on moving everything around ;)

Removed the need for a engineconfigurationwrapper

---

src/MigrationTools.Clients.AzureDevops.ObjectModel/Enrichers/TfsWorkItemLinkEnricher.cs

Added `if (targetWorkItemLinkStart.Id == "0")` to Enricher rather than exception.

targetWorkItemLinkStart.Id == "0

---

src/MigrationTools.Clients.AzureDevops.ObjectModel/Processors/TfsSharedQueryProcessorOptions.cs

Same Issue as TfsTeamSettingsProcessorOptions.
closes #759

Fixed TfsSharedQueryProcessorOptions

---

docs/Reference/Generated/MigrationTools.Clients.AzureDevops.ObjectModel.xml
docs/Reference/ProcessorEnrichers/TfsNodeStructure.json
docs/Reference/ProcessorEnrichers/TfsNodeStructure.md
src/MigrationTools.Clients.AzureDevops.ObjectModel/Enrichers/TfsNodeStructure.cs
src/MigrationTools.Clients.AzureDevops.ObjectModel/Enrichers/TfsNodeStructureOptions.cs
src/MigrationTools.Clients.AzureDevops.ObjectModel/Processors/TfsTeamSettingsProcessor.cs
src/MigrationTools.Clients.AzureDevops.ObjectModel/ServiceCollectionExtensions.cs
src/MigrationTools/ProcessorEnrichers/WorkItemProcessorEnrichers/WorkItemProcessorEnricher.cs
src/VstsSyncMigrator.Core/Execution/MigrationContext/WorkItemMigrationContext.cs

This adds the TfsNodeStructure Enricher to work with TfsTeamSettings Processor.
Is can be used like this:

Added TfsNodeStructure Enricher

---

src/MigrationTools.Clients.AzureDevops.ObjectModel/_Enginev1/Clients/TfsWorkItemMigrationClient.cs

RemoveExtraQuery

---

src/MigrationTools.Clients.AzureDevops.ObjectModel/Enrichers/TfsWorkItemLinkEnricher.cs

Another crash related to those pesky "unrecognized resource links".

Don't crash on unrecognized resource link

---

docs/Reference/Generated/MigrationTools.Clients.AzureDevops.Rest.xml
src/MigrationTools.Clients.AzureDevops.Rest/Endpoints/AzureDevOpsEndpoint.cs
src/MigrationTools.Clients.AzureDevops.Rest/MigrationTools.Clients.AzureDevops.Rest.csproj
src/MigrationTools.Clients.AzureDevops.Rest/Processors/AzureDevOpsPipelineProcessor.cs
src/MigrationTools/DataContracts/Mapping.cs
src/MigrationTools/DataContracts/Pipelines/DeploymentGroup.cs
src/MigrationTools/DataContracts/Pipelines/ReleaseDefinitions.cs
src/MigrationTools/DataContracts/Pipelines/TaskAgentPool.cs
src/MigrationTools/DataContracts/Pipelines/VariableGroups.cs

and some other code refactorings

pipeline processor, tweeks to get my release def migration to work

---

docs/Reference/Processors/TfsTeamSettingsProcessor.json

Update sample JSON configuration

---

docs/Reference/Processors/TfsTeamSettingsProcessor.md

Update example JSON embedded on page

---

src/MigrationTools.Clients.AzureDevops.ObjectModel/Processors/TfsSharedQueryProcessor.cs

Bugfix: replace old custom fields in WI query.

Bugfix TfsSharedQueryProcessor.cs

---

configuration.json
src/MigrationTools.Clients.AzureDevops.ObjectModel.Tests/Endpoints/TfsWorkItemEndPointTests.cs
src/MigrationTools.Clients.AzureDevops.ObjectModel.Tests/MigrationTools.Clients.AzureDevops.ObjectModel.Tests.csproj
src/MigrationTools.Clients.AzureDevops.ObjectModel/MigrationTools.Clients.AzureDevops.ObjectModel.csproj
src/MigrationTools.Clients.AzureDevops.Rest.Tests/MigrationTools.Clients.AzureDevops.Rest.Tests.csproj
src/MigrationTools.Clients.AzureDevops.Rest/MigrationTools.Clients.AzureDevops.Rest.csproj
src/MigrationTools.Clients.FileSystem.Tests/MigrationTools.Clients.FileSystem.Tests.csproj
src/MigrationTools.Clients.InMemory.Tests/MigrationTools.Clients.InMemory.Tests.csproj
src/MigrationTools.Host.Tests/MigrationTools.Host.Tests.csproj
src/MigrationTools.Host/MigrationTools.Host.csproj
src/MigrationTools.Integration.Tests/MigrationTools.Integration.Tests.csproj
src/MigrationTools.TestExtensions/MigrationTools.TestExtensions.csproj
src/MigrationTools.Tests/MigrationTools.Tests.csproj
src/MigrationTools/MigrationTools.csproj
src/MigrationTools/Tests/TestingConstants.cs
src/VstsSyncMigrator.Core.Tests/VstsSyncMigrator.Core.Tests.csproj
src/VstsSyncMigrator.Core/Execution/MigrationContext/TestPlansAndSuitesMigrationContext.cs
src/VstsSyncMigrator.Core/VstsSyncMigrator.Core.csproj

Steps to remediate:
1. Updated all dependencies
2. ?
3. Profit

852-SaveNewTestSuiteToPlan-Active

---

src/MigrationTools.Clients.AzureDevops.ObjectModel/ProcessorEnrichers/TfsNodeStructure.cs

One of our projects has the word "area" in its name. So when `TfsNodeStructure.ProcessCommonStructure` tries to find the correct node (i.e. `Area` or `Iterations`), it finds more than one node for `Area` because the source query uses `node.Path.Contains` which matches all of the available nodes. 
```
_sourceRootNodes[0].Path
"\\Fishing_Areas\\Iteration"
_sourceRootNodes[1].Path
"\\Fishing_Areas\\Area"
```
This fixes the issue by looking for the full source path.

Fix TfsNodeStructure crash when project includes treeTypeSource name

---

configuration.json
src/MigrationTools/Tests/TestingConstants.cs
src/VstsSyncMigrator.Core/Execution/MigrationContext/TestPlansAndSuitesMigrationContext.cs

Updated all new Static Test Suits to "In Progress" before savinf to a void faults. Also removed "In Progress" mapping from the default config.

TestPlansAndSuitesMigrationContext Fix for Invalid States

---

src/MigrationTools.Clients.AzureDevops.Rest/Endpoints/AzureDevOpsEndpoint.cs
src/MigrationTools.Clients.AzureDevops.Rest/Processors/AzureDevOpsPipelineProcessor.cs

This PR should make the PipelineProcessor runnable again.
closes #876

Fix PipelineProcessor

---

src/VstsSyncMigrator.Core/Execution/MigrationContext/TestPlansAndSuitesMigrationContext.cs

Added log to Test Plans and Suits to show when Plans are skipped.

Update to write our log for plans that are skipped.

---

MigrationTools.sln
README.md
docs/Processors/WorkItemMigrationConfig.md
docs/Reference/ProcessorEnrichers/TfsRevisionManager.json
docs/Reference/ProcessorEnrichers/TfsRevisionManager.md
docs/configuration.md
src/MigrationTools.Clients.AzureDevops.ObjectModel.Tests/ProcessorEnrichers/TfsRevisionManagerTests.cs
src/MigrationTools.Clients.AzureDevops.ObjectModel.Tests/ServiceProviderHelper.cs
src/MigrationTools.Clients.AzureDevops.ObjectModel/ProcessorEnrichers/TfsRevisionManager.cs
src/MigrationTools.Clients.AzureDevops.ObjectModel/ProcessorEnrichers/TfsRevisionManagerOptions.cs
src/MigrationTools.Clients.AzureDevops.ObjectModel/ServiceCollectionExtensions.cs
src/MigrationTools.Extension/README.md
src/MigrationTools/_EngineV1/Configuration/Processing/WorkItemMigrationConfig.cs
src/VstsSyncMigrator.Core/Execution/MigrationContext/WorkItemMigrationContext.cs

Refactored revision manager to have more tests and support limiting the number of revisions. CollapseRevisions has been replaced by setting MaxRevisions to 1 and setting AttachRevisionHistory to true;
Config Change:  +semver: minor
Remove: CollapseRevisions
Added: AttachRevisionHistory

Revision manager tests

---

src/MigrationTools.Clients.AzureDevops.Rest/Processors/AzureDevOpsPipelineProcessor.cs
src/MigrationTools/DataContracts/Pipelines/GitRepository.cs

This will only work if the Name of the Repository is the same in both the source and target Project. Support of Repo mapping will be added later on.
closes #876

Fix repo mapping issue

---

src/MigrationTools.Clients.AzureDevops.ObjectModel.Tests/MigrationTools.Clients.AzureDevops.ObjectModel.Tests.csproj
src/MigrationTools.Clients.AzureDevops.Rest.Tests/MigrationTools.Clients.AzureDevops.Rest.Tests.csproj
src/MigrationTools.Clients.FileSystem.Tests/MigrationTools.Clients.FileSystem.Tests.csproj
src/MigrationTools.Clients.InMemory.Tests/MigrationTools.Clients.InMemory.Tests.csproj
src/MigrationTools.Host.Tests/MigrationTools.Host.Tests.csproj
src/MigrationTools.Host/MigrationTools.Host.csproj
src/MigrationTools.Integration.Tests/MigrationTools.Integration.Tests.csproj
src/MigrationTools.TestExtensions/MigrationTools.TestExtensions.csproj
src/MigrationTools.Tests/MigrationTools.Tests.csproj
src/MigrationTools/MigrationTools.csproj
src/VstsSyncMigrator.Core.Tests/VstsSyncMigrator.Core.Tests.csproj
src/VstsSyncMigrator.Core/VstsSyncMigrator.Core.csproj

exept for the microsoft extensions that bumped to 6

updated all nuget packages to latest version, mostly minor changes

---

src/VstsSyncMigrator.Core/Execution/MigrationContext/WorkItemMigrationContext.cs

#1064 Fix "condition is always true"

---

configuration2.json
src/MigrationTools.Clients.AzureDevops.ObjectModel.Tests/Endpoints/TfsWorkItemEndPointTests.cs
src/MigrationTools.Clients.AzureDevops.ObjectModel.Tests/Processors/TfsSharedQueryProcessorTests.cs
src/MigrationTools.Clients.AzureDevops.ObjectModel/Endpoints/TfsWorkItemEndpoint.cs
src/MigrationTools.Clients.AzureDevops.ObjectModel/ProcessorEnrichers/TfsNodeStructure.cs
src/MigrationTools.Clients.AzureDevops.ObjectModel/Processors/TfsAreaAndIterationProcessor.cs
src/MigrationTools.Clients.AzureDevops.ObjectModel/Processors/TfsAreaAndIterationProcessorOptions.cs
src/MigrationTools.Clients.AzureDevops.ObjectModel/Processors/TfsTeamSettingsProcessorOptions.cs
src/MigrationTools.Clients.AzureDevops.ObjectModel/ServiceCollectionExtensions.cs
src/MigrationTools.Clients.AzureDevops.ObjectModel/_Enginev1/Clients/TfsWorkItemMigrationClient.cs
src/MigrationTools.Clients.AzureDevops.ObjectModel/_Enginev1/Clients/TfsWorkItemQuery.cs
src/MigrationTools.Clients.FileSystem/Endpoints/FileSystemWorkItemQuery.cs
src/MigrationTools.Integration.Tests/ServiceProviderHelper.cs
src/MigrationTools/Endpoints/IWorkItemQuery.cs
src/MigrationTools/Options/QueryOptions.cs
src/MigrationTools/Processors/Processor.cs
src/MigrationTools/Processors/WorkItemProcessor/WorkItemTrackingProcessor.cs
src/MigrationTools/_EngineV1/Clients/IWorkItemQueryBuilder.cs
src/MigrationTools/_EngineV1/Clients/IWorkItemQueryBuilderFactory.cs
src/MigrationTools/_EngineV1/Clients/WorkItemMigrationClientBase.cs
src/MigrationTools/_EngineV1/Clients/WorkItemQueryBase.cs
src/MigrationTools/_EngineV1/Clients/WorkItemQueryBuilder.cs
src/MigrationTools/_EngineV1/Clients/WorkItemQueryBuilderFactory.cs
src/MigrationTools/_EngineV1/Processors/StaticProcessorBase.cs
src/VstsSyncMigrator.Core/Execution/MigrationContext/WorkItemMigrationContext.cs
src/VstsSyncMigrator.Core/Execution/MigrationContext/WorkItemPostProcessingContext.cs
src/VstsSyncMigrator.Core/Execution/ProcessingContext/CreateTeamFolders.cs
src/VstsSyncMigrator.Core/Execution/ProcessingContext/WorkItemUpdateAreasAsTagsContext.cs

trying to limit the usage of IServiceProvider around in the code

Code cleanup,  IServiceProvider, and bugfixes on v2

---

docs/changeset-migration.md

Replaced the old way to start migraton.exe with the new necessary configuration file changes needed to user Changeset Migration.

Added Changeset Migration config line

---

src/MigrationTools.Clients.AzureDevops.ObjectModel/Enrichers/TfsWorkItemEmbededLinkEnricher.cs

Minor fix to yesterday's PR #1120

Minor fix to yesterday's PR #1120

---

src/MigrationTools.Clients.AzureDevops.ObjectModel/TfsExtensions.cs
src/MigrationTools.Clients.AzureDevops.ObjectModel/_Enginev1/Clients/TfsWorkItemMigrationClient.cs
src/MigrationTools.Clients.AzureDevops.ObjectModel/_Enginev1/Clients/TfsWorkItemQuery.cs
src/MigrationTools.Clients.FileSystem/Endpoints/FileSystemWorkItemQuery.cs
src/MigrationTools.Tests/Core/Clients/WorkItemMigrationClientMock.cs
src/MigrationTools/Endpoints/IWorkItemQuery.cs
src/MigrationTools/_EngineV1/Clients/IWorkItemMigrationClient.cs
src/MigrationTools/_EngineV1/Clients/WorkItemMigrationClientBase.cs
src/MigrationTools/_EngineV1/Clients/WorkItemQueryBase.cs
src/VstsSyncMigrator.Core/Execution/ProcessingContext/WorkItemDelete.cs

since delete only needs the id, adding a feature for getting only workitem ids based on query.
Also deleting multiple items in the same call, for less calls over the wire

major improvements to speed for delete workitems

---

src/MigrationTools/DataContracts/Pipelines/BuildDefinitions.cs

Adding properties for managing Queue and Agent identifier during pipeline migration.

Include Queue and Agent properties for pipeline migration

---

src/MigrationTools/DataContracts/Pipelines/ServiceConnection.cs

To migrate AzureRM service connections (with auto auth), some parameters of the source connection have to be removed.

Fixes #1199

---

src/MigrationTools.Clients.AzureDevops.Rest/Processors/AzureDevOpsPipelineProcessor.cs

Fix #1209  missing service connection as task input after migration of release pipeline.

Fixes #1209 missing service connection mapping

---

src/MigrationTools.Clients.AzureDevops.ObjectModel/_Enginev1/Clients/TfsWorkItemMigrationClient.cs

bugfix for cross project linking 

---

src/MigrationTools.Clients.AzureDevops.Rest.Tests/MigrationTools.Clients.AzureDevops.Rest.Tests.csproj
src/MigrationTools.Clients.FileSystem.Tests/MigrationTools.Clients.FileSystem.Tests.csproj
src/MigrationTools.Clients.InMemory.Tests/MigrationTools.Clients.InMemory.Tests.csproj
src/MigrationTools.ConsoleCore/MigrationTools.ConsoleCore.csproj
src/MigrationTools.Host.Tests/MigrationTools.Host.Tests.csproj
src/MigrationTools.Tests/MigrationTools.Tests.csproj

since net6 is the new lts version, upgraded all projects targeting net3.1 to net6

upgraded to latest lts

---

src/MigrationTools.Clients.AzureDevops.Rest/Endpoints/AzureDevOpsEndpoint.cs
src/MigrationTools.Clients.AzureDevops.Rest/Processors/KeepOutboundLinkTargetProcessor.cs
src/MigrationTools.Clients.AzureDevops.Rest/Processors/KeepOutboundLinkTargetProcessorOptions.cs
src/MigrationTools.Clients.AzureDevops.Rest/ServiceCollectionExtensions.cs
src/MigrationTools/DataContracts/WorkItems/WorkItem.cs

for usage when wanting to keep the link to the an external workitem the same in both source and target

adding a draft keep link processor

---

src/MigrationTools.Clients.AzureDevops.ObjectModel/Endpoints/TfsWorkItemConvertor.cs
src/MigrationTools.Clients.AzureDevops.ObjectModel/Enrichers/TfsWorkItemLinkEnricher.cs
src/MigrationTools.Clients.AzureDevops.ObjectModel/FieldMaps/RegexFieldMap.cs
src/VstsSyncMigrator.Core/Execution/MigrationContext/WorkItemMigrationContext.cs

This commit allows user names to be mapped with field mappings, including regular expressions.

Support field mappings for user names

---

src/MigrationTools.Host/StartupService.cs

Added a skipVersionCheck to the command args

---

CONTRIBUTING.md
docs/Processors/FixGitCommitLinksConfig.md
docs/Processors/HtmlFieldEmbeddedImageMigrationConfig.md
docs/Processors/TestConfigurationsMigrationConfig.md
docs/Processors/TestPlansAndSuitesMigrationConfig.md
docs/Processors/TestVariablesMigrationConfig.md
docs/Processors/TestVeriablesMigrationConfig.md
docs/Processors/WorkItemMigrationConfig.md
docs/Processors/WorkItemUpdateAreasAsTagsConfig.md
docs/Processors/WorkItemUpdateConfig.md
docs/Reference/EndpointEnrichers/index.md
docs/Reference/index.md
docs/configuration.md
docs/faq.md
docs/index.md

* Add link to AzureDevOpsPipelineProcessorOptions
* Add json example for TestPlansAndSuitesMigrationConfig 
* Correct spelling

Update documentation and correct spelling

---

docs/Reference/Generated/MigrationTools.xml
docs/Reference/v1/Processors/TestPlansAndSuitesMigrationContext.md
docs/Reference/v1/Processors/WorkItemMigrationContext.json
docs/Reference/v1/Processors/WorkItemMigrationContext.md
src/MigrationTools/_EngineV1/Configuration/Processing/WorkItemMigrationConfig.cs
src/VstsSyncMigrator.Core/Execution/MigrationContext/WorkItemMigrationContext.cs

This is a +semver: minor moment as `NodeStructureEnricherEnabled` has been removed from the config.

Remove node structure enricher enabled

---

README.md
docs/index.md

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change and mention if your change updated any configuration file elements.
Fixes # (issue)
- **Logging uses serilog** - All Logging should be in the format `"My message that contains {item} and {item2}", item, itesm2`! Do not use `$"My message that contains {item} and {item2}"` to pass text into the log strings as this disables [Serilog](https://serilog.net/)'s ability to pass that data as telemetry to Application Insights and for log highlighting.
Please delete options that are not relevant.
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant …

Updated stats

---

src/MigrationTools.Clients.AzureDevops.Rest/Processors/AzureDevOpsPipelineProcessor.cs

Fixed incorrect condition during build pipeline migration

Fixed incorrect condition

---

src/VstsSyncMigrator.Core/Execution/MigrationContext/TestPlansAndSuitesMigrationContext.cs

Issue 1500 : Requirements based test suite based on requirement of work item type Bug not migrated.
This code implements a workaround and does replace the failing soap api call with a rest api call.

Issue 1500 : Requirements based test suite based on requirement of work item type Bug not migrated

---

docs/Reference/Generated/MigrationTools.Clients.AzureDevops.Rest.xml
src/MigrationTools.Clients.AzureDevops.Rest/Endpoints/AzureDevOpsEndpoint.cs
src/MigrationTools.Clients.AzureDevops.Rest/Processors/AzureDevOpsPipelineProcessor.cs

This PR should fix #1510 and adds a temporary fix for the service connection migration problem

Pipeline migration fixes

---

src/VstsSyncMigrator.Core/Execution/MigrationContext/WorkItemMigrationContext.cs

Workaround for work items that have changed from work item type during their life cycle.

#1535 : WI Migration - WI Type changes not recovered

---

src/MigrationTools.Clients.AzureDevops.ObjectModel/Enrichers/TfsWorkItemLinkEnricher.cs
src/VstsSyncMigrator.Core/Execution/MigrationContext/WorkItemMigrationContext.cs

Added functionality to migrate the shared parameters for a test case.
Have changed the migration logic for migration of shared steps and shared parameters for test cases to be migrated even if links are not migrated.

#1561 Shared steps and shared parameters are not migrated when links are not migrated

---

src/MigrationTools.Clients.AzureDevops.ObjectModel/ProcessorEnrichers/TfsNodeStructure.cs

missing '!'

---

src/MigrationTools.ConsoleFull/Properties/launchSettings.json
src/MigrationTools.Host/CommandLine/ExecuteOptions.cs
src/MigrationTools.Host/MigrationToolHost.cs
src/MigrationTools.Host/StartupService.cs

The system now works to allow the diable of telemetry via the --disableTelemetery option

Updated to fix telemitery exception.

---

configuration.json
src/MigrationTools.Host/MigrationToolHost.cs

Fix for bug that @RehabAbotalep found in the Init function that was introduced when we enabled the bypass... and no one noticed ;)
Fix for #1669

Fix for bug that @RehabAbotalep found in the Init function

---

src/VstsSyncMigrator.Core/Execution/MigrationContext/TestPlansAndSuitesMigrationContext.cs

Updated `FindSuiteEntry` and `FindTestPlan` to check the work item found only by the title also has a matching `ReflectedWorkItemId`. This should prevent eronious suits and plans ofthe name name from getting picked.
For @soumyanath-datta-v and @potrusaikiran @saikiranpotru-vialto

Updated `FindSuiteEntry` and `FindTestPlan` to check the work item `ReflectedWorkItemId`

---

README.md
docs/_data/reference.v1.processors.workitemmigrationcontext.yaml
docs/collections/_reference/reference.v1.processors.exportusersformapping.md
docs/collections/_reference/reference.v1.processors.workitemmigrationcontext.md
docs/collections/_reference/reference.v2.endpoints.tfsworkitemendpoint.md
docs/faq.md
docs/getting-started.md
docs/index.md
src/MigrationTools.Clients.AzureDevops.ObjectModel.Tests/MigrationTools.Clients.AzureDevops.ObjectModel.Tests.csproj
src/MigrationTools.Clients.AzureDevops.Rest.Tests/MigrationTools.Clients.AzureDevops.Rest.Tests.csproj
src/MigrationTools.Clients.FileSystem.Tests/MigrationTools.Clients.FileSystem.Tests.csproj
src/MigrationTools.Clients.InMemory.Tests/MigrationTools.Clients.InMemory.Tests.csproj
src/MigrationTools.ConsoleDataGenerator/MigrationTools.ConsoleDataGenerator.csproj
src/MigrationTools.ConsoleFull/MigrationTools.ConsoleFull.csproj
src/MigrationTools.Extension/README.md
src/MigrationTools.Host.Tests/MigrationTools.Host.Tests.csproj
src/MigrationTools.Host/MigrationTools.Host.csproj
src/MigrationTools.Host/Services/DetectVersionService.cs
src/MigrationTools.Host/StartupService.cs
src/MigrationTools.Integration.Tests/MigrationTools.Integration.Tests.csproj
src/MigrationTools.Tests/MigrationTools.Tests.csproj
src/MigrationTools/_EngineV1/Configuration/EngineConfigurationBuilder.cs
src/VstsSyncMigrator.Core.Tests/VstsSyncMigrator.Core.Tests.csproj

Updating all documentation to reflect a Winget path instead of a Choco path +semver: major

Migrate to winget and change exe name to `devops-migration`

---

MigrationTools.lutconfig
src/MigrationTools.ConsoleFull/Properties/launchSettings.json
src/MigrationTools.Host.Tests/Services/DetectVersionService2Tests.cs
src/MigrationTools.Host/MigrationToolHost.cs
src/MigrationTools.Host/Services/DetectVersionService2.cs
src/MigrationTools.Host/Services/IDetectVersionService2.cs
src/MigrationTools.Host/StartupService.cs

Working to enable auto detect and update of the package through Winget.
Outstanding https://github.com/basicx-StrgV/WGet.NET/issues/23

Winget Auto-Update & Install

---

src/MigrationTools.ConsoleFull/Properties/launchSettings.json
src/MigrationTools.Host.Tests/Services/DetectVersionService2Tests.cs
src/MigrationTools.Host.Tests/Services/DetectVersionServiceTests.cs
src/MigrationTools.Host/MigrationToolHost.cs
src/MigrationTools.Host/MigrationTools.Host.csproj
src/MigrationTools.Host/Services/DetectVersionService2.cs
src/MigrationTools.Host/StartupService.cs

Update to fix the failing tests so that they skipp on Wisnowd Server runs

Fix failing tests

---

README.md
configuration.json
docs/Reference/Generated/MigrationTools.xml
docs/Reference/v1/Processors/WorkItemMigrationContext-notes.md
docs/_data/reference.v1.processors.workitemmigrationcontext.yaml
docs/_includes/sampleConfig/configuration-WorkItemTracking.json
docs/_includes/sampleConfig/configuration-full.json
docs/_includes/sampleConfig/configuration.json
docs/collections/_reference/reference.v1.processors.workitemmigrationcontext.md
src/MigrationTools.Host/StartupService.cs
src/MigrationTools.Samples/configuration-for-copy.json
src/MigrationTools/_EngineV1/Configuration/Processing/WorkItemMigrationConfig.cs
src/VstsSyncMigrator.Core/Execution/MigrationContext/WorkItemMigrationContext.cs

Remove stop migration on missing area iteration nodes

---

docs/Reference/Generated/MigrationTools.Host.xml
src/MigrationTools.ConsoleFull/Properties/launchSettings.json
src/MigrationTools.Host/CommandLine/InitOptions.cs
src/MigrationTools.Host/CommandLine/OptionsMode.cs
src/MigrationTools.Host/InitHostedService.cs
src/MigrationTools/_EngineV1/Configuration/EngineConfigurationBuilder.cs
src/MigrationTools/_EngineV1/Configuration/IEngineConfigurationBuilder.cs
src/MigrationTools/_EngineV1/Configuration/Processing/WorkItemMigrationConfig.cs
src/VstsSyncMigrator.Core/Execution/MigrationContext/WorkItemMigrationContext.cs

This fixes #1725, or at least warns the user of the issue.
PAT's are required when using ADO...

Update to check for missing pat!

---

src/VstsSyncMigrator.Core/Execution/MigrationContext/WorkItemMigrationContext.cs

Bugfix for exceptions when migrating revisions with changed type and the configuration is set to "SkipToFinalRevisedWorkItemType": true. Removed usage of "SkipToFinalRevisedWorkItemType" confuguration. A Check for Work Item ID > 0 before updating is added. "ChangedBy" field is added when inserting the new changed type revision. (#1756 )

#1756 Bugfix for exceptions when migrating revisions with changed type and the configuration is set to "SkipToFinalRevisedWorkItemType": true

---

docs/Reference/Generated/MigrationTools.Host.xml
src/MigrationTools.Clients.AzureDevops.ObjectModel/ProcessorEnrichers/TfsNodeStructure.cs
src/MigrationTools/DataContracts/NodeStructureMissingItem.cs

This should fix #1826, #1838
fix from: @FokkoVeegens:
> missingItem.sourcePath contains a value like:
> `{teamproject}\\2024\\Sprints\\Sprint 01`
> But it should be:
> `\\{teamproject}\\Iteration\\2024\\Sprints\\Sprint 01`
> And then it works.

Change Source Iteration lookup to system path.

---

src/MigrationTools.Tests/ProcessorEnrichers/StringManipulatorEnricherTests.cs
src/MigrationTools.Tests/ServiceProviderHelper.cs
src/MigrationTools/ProcessorEnrichers/WorkItemProcessorEnrichers/StringManipulatorEnricher.cs

Added 4 Unit tests...
1) Create StringManipulatorEnricher
2) String field too long
3) String field is shortter than max
4) Apply regex manipulator
Should resolve #1950

[preview] fix string bug

---

src/VstsSyncMigrator.Core/Execution/MigrationContext/TestPlansAndSuitesMigrationContext.cs

Updated Test Plans and Suits to use the new safe common enricher import to fix #1983

[preview] Updated Test Plans and Suits to use the new safe Common Enricher method

---

configuration.json
src/MigrationTools.Clients.AzureDevops.ObjectModel/Processors/TfsTeamSettingsProcessor.cs
src/MigrationTools/ConfigException.cs
src/VstsSyncMigrator.Core/Execution/MigrationContext/ConfigException.cs
src/VstsSyncMigrator.Core/Execution/MigrationContext/WorkItemMigrationContext.cs

Fix for nodeStructureEnricher being turned off but needed

[preview] Fix for nodeStructureEnricher being turned off but needed

---

src/MigrationTools.Clients.AzureDevops.ObjectModel/ProcessorEnrichers/TfsUserMappingEnricher.cs

[preview] Fix for #1997

---

configuration.json
src/MigrationTools.Clients.AzureDevops.ObjectModel/MigrationTools.Clients.AzureDevops.ObjectModel.csproj
src/MigrationTools.Clients.AzureDevops.ObjectModel/ProcessorEnrichers/TfsNodeStructureOptions.cs
src/MigrationTools.Host/MigrationToolHost.cs
src/MigrationTools/Helpers/NewtonsoftHelpers.cs
src/MigrationTools/MigrationTools.csproj
src/MigrationTools/ProcessorEnrichers/ProcessorEnricherOptions.cs
src/MigrationTools/_EngineV1/Configuration/EngineConfigurationBuilder.cs

Added a new config validator. Currently validates only missing items, and not extra ones.

[preview] Config Validator

---

src/VstsSyncMigrator.Core/Execution/MigrationContext/WorkItemMigrationContext.cs

a posible fix for #1959 is to update closeddate first. before state!

[preview] a posible fix for #1959 is to update closeddate first. before state!

---

configuration.json
docs/Reference/Generated/MigrationTools.Clients.AzureDevops.ObjectModel.xml
docs/_data/reference.v1.processors.workitemmigrationcontext.yaml
docs/_data/reference.v2.processorenrichers.tfsteamsettingsenricher.yaml
docs/collections/_reference/reference.v1.processors.workitemmigrationcontext.md
docs/collections/_reference/reference.v2.processorenrichers.tfsteamsettingsenricher.md
src/MigrationTools.Clients.AzureDevops.ObjectModel/ProcessorEnrichers/TfsTeamSettingsEnricher.cs
src/MigrationTools.Clients.AzureDevops.ObjectModel/ProcessorEnrichers/TfsTeamSettingsEnricherOptions.cs
src/MigrationTools.Clients.AzureDevops.ObjectModel/ServiceCollectionExtensions.cs
src/MigrationTools.Clients.AzureDevops.ObjectModel/TfsExtensions.cs
src/MigrationTools.Clients.AzureDevops.ObjectModel/_Enginev1/Clients/TfsMigrationClient.cs
src/MigrationTools.Tests/Core/Clients/MigrationClientMock.cs
src/MigrationTools/_EngineV1/Clients/IMigrationClient.cs
src/MigrationTools/_EngineV1/DataContracts/ProjectData.cs
src/VstsSyncMigrator.Core/Execution/MigrationContext/WorkItemMigrationContext.cs

Added Team Settings as an Enricher so that it can be run as part of the WorkItemMigration

[preview] Enable Team Setting Migration At Work Item Time

---

.github/workflows/main.yml
src/MigrationTools.ConsoleFull/MigrationTools.ConsoleFull.csproj
src/MigrationTools.Host/MigrationToolHost.cs
src/MigrationTools.Host/Services/DetectVersionService2.cs
src/MigrationTools.Host/StartupService.cs
src/MigrationTools/StaticVariables.cs

- Moved to version detection through Informational Version with full path
- Used FullSemVer regex to split out if we run on a branch or local.
- Write out really version number
- use version number to detect if we are preview or local
Inlcudes fix for #2144

Make Winget name Dynamic and better version detection

---

.github/workflows/main.yml
build/azure-pipeline.yml

Update to remove preview tags for both ADO and GitHub

Dont build preview tags, only release

---

.github/labeler.yml
.github/release.yml
.github/workflows/code-review.yml
.github/workflows/labeler.yml
.github/workflows/main.yml
.github/workflows/open-pr-describer.yml
.github/workflows/opencommit.yml

🔧 (release.yml): update changelog configuration to reflect architecture improvements
🔧 (main.yml): add WingetApplicationId to workflow for better deployment tracking
The changelog configuration now categorizes changes labeled as "architecture" under "Architecture Improvements" for better clarity. The workflow file is updated to include the WingetApplicationId, which helps in tracking and managing deployments via Winget. This ensures that the correct application ID is used based on the release ring, improving deployment accuracy and traceability.

Update to build to better setup release.

---

.github/labeler.yml
.github/workflows/main.yml

🔧 (main.yml): update conditional checks to compare against 'true' string
The conditional checks in the GitHub Actions workflow are updated to compare against the string 'true' instead of a boolean. This ensures that the conditions are evaluated correctly, as the outputs from the Setup job are strings.

Fix Detetion

---

.github/label-actions.yml

Enhance the issue templates to provide clearer guidance for users. The updated templates include links to the latest and preview versions of the tools, and detailed steps for generating logs and debugging locally. This aims to streamline the troubleshooting process and improve user support.

📝 (label-actions.yml): update issue templates with detailed instructions

---

docs/Reference/Generated/MigrationTools.xml
src/MigrationTools.Clients.AzureDevops.ObjectModel/ProcessorEnrichers/TfsNodeStructure.cs
src/VstsSyncMigrator.Core/Execution/MigrationContext/WorkItemMigrationContext.cs

💡 (TfsNodeStructure.cs): improve log message clarity
Enhance the log message in TfsNodeStructure.cs to provide better clarity by including a newline character for improved readability. This makes the log output easier to understand when debugging.
💡 (WorkItemMigrationContext.cs): add additional context to log message
Improve the log message in WorkItemMigrationContext.cs to include the count of source work items being checked for migration. This provides more context in the logs, making it easier to understand the migration process. Additionally, ensure the project name is replaced in the WIQL query before running it, which enhances the accuracy of the migration process.

fix #2294 for @NormanGarciaV

---

docs/Reference/Generated/MigrationTools.xml
src/MigrationTools.Clients.AzureDevops.Rest/MigrationTools.Clients.AzureDevops.Rest.csproj
src/MigrationTools.Clients.FileSystem/MigrationTools.Clients.FileSystem.csproj
src/MigrationTools.Clients.TfsObjectModel/MigrationTools.Clients.TfsObjectModel.csproj
src/MigrationTools.ConsoleCore/MigrationTools.ConsoleCore.csproj
src/MigrationTools.ConsoleFull/MigrationTools.ConsoleFull.csproj
src/MigrationTools.ConsoleFull/Program.cs
src/MigrationTools.ConsoleFull/Properties/launchSettings.json
src/MigrationTools.Host/BoilerplateCli.cs
src/MigrationTools.Host/Commands/CommandBase.cs
src/MigrationTools.Host/Commands/ExecuteMigrationCommand.cs
src/MigrationTools.Host/Commands/InitMigrationCommand.cs
src/MigrationTools.Host/Commands/UpgradeConfigCommand.cs
src/MigrationTools.Host/MigrationToolHost.cs
src/MigrationTools.Host/MigrationTools.Host.csproj
src/MigrationTools/MigrationTools.csproj
src/MigrationTools/Services/ActivitySourceProvider.cs

This adds OpenTelemtery to pur stack, and we will eventually remove the OLD AI setup once we figure out how OpenTelemtery works!

Added OpenTelemtery!

---

docs/Reference/Generated/MigrationTools.xml
src/MigrationTools.Host/MigrationToolHost.cs

Change the base directory from the default if the running location to the app install directory.

Ensure loading of AppSettings for defaults.

---

.github/dependabot.yml
.github/workflows/MigrationToolsTelemetery.yml
.github/workflows/labeler.yml
.github/workflows/main.yml
.github/workflows/open-pr-describer.yml
.github/workflows/opencommit.yml
src/MigrationTools.Clients.TfsObjectModel/Tools/TfsUserMappingTool.cs

💡 (TfsUserMappingTool.cs): add debug logging for user identity mapping
Add a debug log statement to track changes in user identity mapping. This helps in tracing the mapping process by logging the original and new values, which is useful for debugging and ensuring the mapping logic is functioning as expected.

UserMpaping shenanigans

---

src/MigrationTools.Clients.TfsObjectModel/Tools/FieldMappingTool/FieldMaps/FieldToFieldMap.cs

Improve `FieldToFieldMap` according to #2437.

adjust handling of default value

---

docs/Reference/Generated/MigrationTools.xml
src/MigrationTools.Clients.TfsObjectModel/EndPoints/Infrastructure/TfsTeamProjectAuthentication.cs
src/MigrationTools.Clients.TfsObjectModel/Endpoints/TfsEndpointOptions.cs
src/MigrationTools.Clients.TfsObjectModel/Endpoints/TfsLanguageMapOptions.cs
src/MigrationTools.Clients.TfsObjectModel/Processors/TfsWorkItemMigrationProcessorOptionsValidator.cs
src/MigrationTools.Clients.TfsObjectModel/Tools/TfsGitRepositoryToolOptionsValidator.cs
src/MigrationTools.Clients.TfsObjectModel/Tools/TfsNodeStructureToolOptions.cs
src/MigrationTools/Options/NetworkCredentialsOptions.cs

📝 (docs): update MigrationTools.xml to reflect latest git metadata
♻️ (logging): integrate Serilog for enhanced debugging in option validators
The MigrationTools.xml file is updated to reflect the latest git metadata, including branch, commit, and version information, ensuring documentation accuracy. The integration of Serilog logging in various option validators across the codebase provides better insight into validation processes, aiding in debugging and improving maintainability.

Add aditional debug writes to validators.

---

src/MigrationTools.Clients.AzureDevops.Rest/Processors/AzureDevOpsPipelineProcessorOptions.cs

Added RepositoryNameMaps as class attribute 

---

src/MigrationTools.Clients.TfsObjectModel/Processors/TfsWorkItemMigrationProcessor.cs

PR based on discussion https://github.com/nkdAgility/azure-devops-migration-tools/discussions/2216#discussioncomment-11511678

Same key item error fix

---

src/MigrationTools.Clients.TfsObjectModel/Tools/FieldMappingTool/FieldMaps/FieldValueMap.cs

#2596 2595 Added null value handling and use the same behaviour as for "null"

#2595 Added null value handling

---

src/MigrationTools.Clients.TfsObjectModel/Tools/TfsGitRepositoryTool.cs
src/MigrationTools.Clients.TfsObjectModel/Tools/TfsGitRepositoryToolOptions.cs

- Added option
- Added code to drop changesets during the migration

Added option to drop changesets during the migration

---

docs/index.md

Added link to External Walkthroughs and Reviews

Added link "Migration Azure DevOps Projects..." to External Walkthroughs and Reviews

---

src/MigrationTools.Clients.TfsObjectModel/Tools/TfsNodeStructureTool.cs

💡 (TfsNodeStructureTool.cs): add detailed logging for node migration process
Enhance logging to provide more detailed information about the node migration process. This includes logging the state of the ReplicateAllExistingNodes option and whether node migration is skipped or executed. The change improves traceability and debugging by providing clear insights into the execution flow and decisions made during the process.

💡feat(TfsNodeStructureTool): Enhance logging for node migration process

---

src/MigrationTools.Clients.TfsObjectModel/Processors/TfsWorkItemMigrationProcessor.cs
src/MigrationTools.Clients.TfsObjectModel/Tools/TfsEmbededImagesTool.cs
src/MigrationTools.Clients.TfsObjectModel/Tools/TfsValidateRequiredFieldTool.cs
src/MigrationTools.ConsoleFull/Properties/launchSettings.json

This pull request refactors the `TfsWorkItemMigrationProcessor` class by removing unused code, improving validation logic, and enhancing logging and telemetry. The changes aim to simplify the codebase, improve maintainability, and provide better insights during execution. Below are the most important changes grouped by theme:
* Removed the `ProgressTimer` class and associated logic, replacing it with simpler calculations for average and remaining time during work item processing. (`src/MigrationTools.Clients.TfsObjectModel/Processors/TfsWorkItemMigrationProcessor.cs`) [[1]](diffhunk://#diff-b0a23408b76051c7078de3664c94b03ef26ca367ede9f084067d8722393f130eL40-L70) [[2]](diffhunk://#diff-b0a23408b76051c7078de3664c94b03ef26ca367ede9f084067d8722393f130eL181) …

Fix for greek letters

---

src/MigrationTools.Clients.TfsObjectModel/Tools/TfsNodeStructureTool.cs
src/MigrationTools.Clients.TfsObjectModel/Tools/TfsNodeStructureToolOptions.cs

Allow to create new root structure nodes (areas, iterations) when there are no sub-nodes

---

docs/_layouts/default.html

- replace Google Analytics script with Google Tag Manager script
- add noscript tag for non-JS environments to improve tracking accuracy

💄 style(html): update Google Tag Manager implementation

---

docs/content/_index.md

📝 docs(content): update site title to reflect content focus
- change title from "Welcome to Our Site" to "Azure DevOps Migration Tools"
- ensure title accurately represents the documentation's subject matter

📝 "Welcome to Our Site" to "Azure DevOps Migration Tools"

---

src/MigrationTools.Extension/README.md

- remove outdated badge from README
- update documentation links to devopsmigration.io
- add detailed installation and support information

📝 docs(README): update links and installation instructions

---

docs/layouts/_shortcodes/class-schema.html

- apply lowercase filter to schema path to prevent case sensitivity issues
- improve compatibility with file systems that are case sensitive

🐛 fix(shortcodes): ensure schema path is lowercase

---

src/MigrationTools.Clients.TfsObjectModel/Tools/TfsAttachmentTool.cs

Fixes #2886 
I fixed it the way, that if adding `originalId` exceeds the comment lengts, this ID is not added and just the comment is saved.
But it migration would be run multiple times, this would duplicate the attachment, because it is searched by presence of this original ID in the comment. So I added another lookup for attachment, which do not search for original ID, but just compares name and comment of the attachment.

Do not save attachments comments longer than 255 characters

---

.vscode/extensions.json
.vscode/launch.json
.vscode/settings.json
.vscode/tasks.json
MigrationTools.slnx
docs/data/classes/reference.tools.tfsworkitemtypevalidatortool.yaml
docs/static/schema/configuration.schema.json
docs/static/schema/schema.tools.tfsworkitemtypevalidatortool.json
src/MigrationTools.Clients.AzureDevops.Rest/Processors/KeepOutboundLinkTargetProcessorOptions.cs

This pull request introduces several improvements to the development tooling and documentation, focusing on better support for Azure Functions, enhancements to the TfsWorkItemTypeValidatorTool configuration, and the addition of a solution structure file. The changes streamline Azure Functions development workflows, clarify configuration options for work item type validation, and add a solution index for better project organization.
**Azure Functions Development Support:**
* Added recommended VS Code extensions for Azure Functions and C# in `.vscode/extensions.json` to improve the developer experience.
* Updated `.vscode/launch.json` with an "Attach to .NET Functions" configuration for easier debugging of Azure Functions.
* Added Azure Functions-specific build, clean, and publish tasks to …

Small tweeks

---

docs/content/docs/how-to/migrating-plans-and-suites/index.md
docs/data/classes/reference.fieldmaps.fieldtofieldmap.yaml
docs/static/schema/configuration.schema.json
docs/static/schema/schema.fieldmaps.fieldtofieldmap.json
docs/static/schema/schema.tools.fieldmappingtool.json
src/MigrationTools.Clients.TfsObjectModel/Tools/FieldMappingTool/FieldMaps/FieldToFieldMap.cs
src/MigrationTools/Tools/FieldMappingTool/FieldMaps/FieldtoFieldMapOptions.cs

This pull request adds a new `fieldMapMode` option to the FieldToFieldMap configuration, allowing users to specify how fields are mapped during migration—either from the source to the target system or between target fields. The update includes code changes, schema updates, documentation, and example configurations to support this new feature.
**Field Mapping Mode Feature:**
* Introduced the `FieldMapMode` enum with `SourceToTarget` and `TargetToTarget` options, and added the `fieldMapMode` property to `FieldToFieldMapOptions`, defaulting to `SourceToTarget`. This allows users to control the direction and context of field mapping. [[1]](diffhunk://#diff-81182bfd75331f6d5d0de7c559392ef9f61f2c0b7636cde99743276795186f21R3-R31) [[2]](diffhunk://#diff-81182bfd75331f6d5d0de7c559392ef9f61f2c0b7636 …

Add fieldMapMode to FieldToFieldMap and update related documentation

---

docs/content/docs/get-started/getting-started/index.md
docs/content/docs/get-started/validation/index.md

This pull request enhances the Azure DevOps Migration Tools documentation by introducing and emphasizing a new "Validation Process" section. The main goal is to guide users through the built-in validation steps that help catch configuration and data issues early, improving migration reliability and reducing errors.
**New Validation Process Documentation:**
* Added a dedicated `validation` page that explains the two-step validation process (pre-data-load and post-data-load), detailing the roles of `TfsWorkItemTypeValidatorTool` and `TfsValidateRequiredFieldTool`. This helps users understand how to verify their setup before migrating data.
**References and Guidance Updates:**
* Added a prominent note and section to the getting started guide, directing users to review the new validation …

Add validation process documentation to getting started guide
